### ISSUE TITLE
N of views compiled.

### ISSUE THREAD

**Issue by freshe** [aspnet/MvcPrecompilation#100]
A bit silly but prior to VS17 i could see how many views where compiled in the output window during publish. Can that be turned on? I found it useful somehow..

**Comment by pranavkm** [comment]
That got removed during some of our refactoring to make the tool from a CLI tool to an msbuild target. We can certainly add more diagnostics in the upcoming release.

**Comment by Eilon** [comment]
We're not currently planning on fixing this, but we're open to contributions for this.

**Comment by mkArtakMSFT** [comment]
We're not going to make any other significant enhancements to this feature, as we'll be replacing it with a better one.
