### ISSUE TITLE
Cross-compiling views between osx.10.11 and win7-x64 fails after moving to csproj/msbuild tooling

### ISSUE THREAD

**Issue by karl-sjogren** [aspnet/MvcPrecompilation#103]
### Functional impact
Precompilation of views fails making our startup times a lot slower.

### Minimal repro steps
Doing this on OSX El Capitan, 10.11.6. My colleague can reproduce it on OSX Sierra, 10.12, as well. A very similar error can be seen if doing it the other way around as well (compiling on Windows for OSX).

1. `dotnet new mvc`
2. Updated csproj to include the following

```
<RuntimeIdentifiers>win7-x64;osx.10.11-x64;osx.10.12-x64</RuntimeIdentifiers>
<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>


<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0" />
```
3. `dotnet restore`
4. `dotnet publish -r win7-x64`

### Expected result
The project would be published and the views compiled.

### Actual result
Viewcompilation fails with the following error.

```
➜  bugrepro dotnet publish -r win7-x64
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  bugrepro -> /Users/karl/src/bugrepro/bin/Debug/netcoreapp1.1/win7-x64/bugrepro.dll
  Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
/Users/karl/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/1.1.0/build/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(25,5): error MSB3073: The command "dotnet exec --runtimeconfig "/Users/karl/src/bugrepro/bin/Debug/netcoreapp1.1/win7-x64/bugrepro.runtimeconfig.json" --depsfile "/Users/karl/src/bugrepro/bin/Debug/netcoreapp1.1/win7-x64/bugrepro.deps.json" "/Users/karl/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/1.1.0/build/netcoreapp1.1/../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj/Debug/netcoreapp1.1/win7-x64/microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 135. [/Users/karl/src/bugrepro/bugrepro.csproj]
```
### Further technical details
This wasn't a problem before moving to the new tooling but still using the same version of `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation`.

**Comment by karl-sjogren** [comment]
A (ugly and slow) workaround for this is available in https://github.com/aspnet/MvcPrecompilation/issues/102#issuecomment-287653103.

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by DenJur** [comment]
I am encountering the same problem with trying to publish for ubuntu from win 7. Here is the error that I am getting:

`C:\Users\name\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0\build\netcoreapp1.1\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(25,5): error MSB3073: The command "dotnet exec --runtimeconfig "C:\TmpProj\bin\Debug\netcoreapp1.1\ubuntu.14.04-x64\TmpProj.runtimeconfig.json" --depsfile "C:\TmpProj\bin\Debug\netcoreapp1.1\ubuntu.14.04-x64\TmpProj.deps.json" "C:\Users\name\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0\build\netcoreapp1.1\../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Debug\netcoreapp1.1\ubuntu.14.04-x64\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450745. [C:\TmpProj\TmpProj.csproj]`

Steps for reproduction are exactly the same as OP.

**Comment by pranavkm** [comment]
Thanks @DenJur \ @karl-sjogren - I haven't gotten around to this as yet - but the primary problem is that we attempt to run the precompilation tool using the app's shared runtime. This clearly does not work when your app targets a runtime from a different OS (a completely valid scenario). The workaround @karl-sjogren has basically involves publishing for the current OS and then re-publishing without having precompilation.

**Comment by Eilon** [comment]
We'll use https://github.com/aspnet/MvcPrecompilation/issues/102 to track the fix for this.
