### ISSUE TITLE
Use the project's Startup so RazorViewEngineOptions can be configured

### ISSUE THREAD

**Issue by tuespetre** [aspnet/MvcPrecompilation#104]
Similar to how `dotnet ef` commands will look for a `Startup` class to pick up configuration, it would be nice if this tool looked for a `Startup` class to pick up configuration for `RazorViewEngineOptions`. For example, we have one application where we have to add metadata references, and because to that, we cannot use view precompilation.

**Comment by pranavkm** [comment]
@tuespetre - we look for an [`IDesignTimeMvcBuilderConfiguration`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/IDesignTimeMvcBuilderConfiguration.cs) type as part of starting up the application. Here's an example of it being used - https://github.com/aspnet/MvcPrecompilation/blob/dev/testapps/ApplicationWithConfigureMvc/Startup.cs#L8

**Comment by tuespetre** [comment]
So it is a thing. You sly 🦊
