### ISSUE TITLE
PreserveCompilationContext not working with netcoreapp2.0 (Windows)

### ISSUE THREAD

**Issue by danwalmsley** [aspnet/MvcPrecompilation#112]
I originally started the bug here:
https://github.com/dotnet/coreclr/issues/10849

I have
'<PreserveCompilationContext>true</PreserveCompilationContext>
in my csproj, when I compile for .netcoreapp1.1 everything works fine, but if I try netcoreapp2.0 it doesn't seem to work.
I get an exception:
Can not find compilation library location for package 'microsoft.netcore.app''

This is with .NET Command Line Tools (2.0.0-preview1-005743)

**Comment by pranavkm** [comment]
@danwalmsley - the tool hasn't been updated to target `netcoreapp2.0` \ `Microsoft.NETCore.App` as yet. We have ongoing work items (https://github.com/aspnet/MvcPrecompilation/pull/106) to update our samples and tests to verify this, but as of now, this isn't fully supported. I'd recommend waiting until we've had a chance to update our projects to target netcoreapp2.0 and verify it before you start using it.

**Comment by Eilon** [comment]
This should all be working in Preview2, which is about to release.
