### ISSUE TITLE
Matching view names becomes case sensitive when precompilation is involved 

### ISSUE THREAD

**Issue by mrahhal** [aspnet/MvcPrecompilation#121]
Some of my view filenames are lower cased. When precompilation is enabled and I try running the published output, finding the view fails with an error:

```
The view 'Index' was not found. The following locations were searched:
...
```

I confirmed by changing the view filenames to what it expects (normal pascal casing) and it started working again.

Problem also occurs when a folder inside "Areas" is cased differently than the `AreaAttribute`'s name.

**Comment by pranavkm** [comment]
Dup of #37. Mvc does case sensitive lookups by default. However if the underlying file system (e.g. the physical file system on Windows) happens to be case-insensitive, you get case insensitive lookups.
