### ISSUE TITLE
can’t use MVC Razor compilation during cross-publish

### ISSUE THREAD

**Issue by shimingsg** [aspnet/MvcPrecompilation#122]
publishing a 'linux' app on a windows machine failed:
1.	Install https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.exe on clean machine(Windows 10)
2.	dotnet new mvc
3.	Add <RuntimeIdentifier>linux-x64</RuntimeIdentifier> to the first PropertyGroup 
4.	dotnet restore & dotnet build
5.	dotnet publish -c Release, failed at this step, the error message as below:
C:\sg\WebApp1>dotnet publish -c Release
Microsoft (R) Build Engine version 15.2.93.5465
Copyright (C) Microsoft Corporation. All rights reserved.

  WebApp1 -> C:\sg\WebApp1\bin\Release\netcoreapp2.0\linux-x64\WebApp1.dll
  Could not find required library hostpolicy.dll in 2 probing paths:

    C:\Users\v-shige\.nuget\packages

    C:\Users\v-shige\.dotnet\NuGetFallbackFolder

  A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\sg\WebApp1\bin\Release\netcoreapp2.0\linux-x64\'.

C:\Users\v-shige\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview1-24647\build\netcoreapp2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(26,5): error MSB3073: The command "dotnet exec --runtimeconfig "C:\sg\WebApp1\bin\Release\netcoreapp2.0\linux-x64\WebApp1.runtimeconfig.json" --depsfile "C:\sg\WebApp1\bin\Release\netcoreapp2.0\linux-x64\WebApp1.deps.json" "C:\Users\v-shige\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview1-24647\build\netcoreapp2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\linux-x64\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450749. [C:\sg\WebApp1\WebApp1.csproj]
dotnet –info output as following:
C:\sg\WebApp1>dotnet --info
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
Version:            2.0.0-preview2-005905
Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.14393
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/MvcPrecompilation/issues/103
