### ISSUE TITLE
Is there a way to minify precompiled cshtml files?

### ISSUE THREAD

**Issue by mrahhal** [aspnet/MvcPrecompilation#124]
Is there some way we can minify those files before being served? A runtime step or a build step?

**Comment by pranavkm** [comment]
Precompilation does the same things as runtime compilation. Since we don't intend on adding runtime support for minification - https://github.com/aspnet/Mvc/issues/3409#issuecomment-269388566 - it's unlikely we'll add support for it during build time compilation.
