### ISSUE TITLE
A single view is not being precompiled.

### ISSUE THREAD

**Issue by i4Contractor** [aspnet/MvcPrecompilation#127]
Error: InvalidOperationException: The view 'GoLive' was not found. The following locations were searched: /Views/Site/GoLive.cshtml
What I believe is happening: For some reason. A single view in a folder of other views is being left out.
What I need to know to test it: Is there some way to see what views are inside of the precompiled dll.

**Comment by i4Contractor** [comment]
I guess I anwsered my own question about the ability to see the views inside. I just opened the dll with visual studio and it opened with the object browser. So the problem is that the view is here, but can't be found.
![image](https://cloud.githubusercontent.com/assets/20428433/26098524/4350d3fe-39e5-11e7-9d5d-d7735a2a48f0.png)

**Comment by rynowak** [comment]
Can I see the code that's *calling* the view. One of the surprising things about precompilation is that it makes view lookup case-sensitive (yes, even on Windows)

**Comment by i4Contractor** [comment]
![image](https://cloud.githubusercontent.com/assets/20428433/26112923/63f7bd6c-3a16-11e7-855d-e9f6f80bbf2e.png)

**Comment by rynowak** [comment]
Yep. There's a casing difference.

`/Views/Site/Golive` (lowercase l)` vs `GoLive` (uppercase L)

**Comment by i4Contractor** [comment]
@rynowak - This seams weird that it works in development, but then breaks when I publish. One might think that is an inconsistency seeing that the windows file system itself is case insensitive.

Is this a bug where case sensitivity has been enabled here, or was that by design. I think consistency is a really important issue. Either it works in development and works in production, or it breaks in development and breaks in production.

**Comment by rynowak** [comment]
I agree that this is not ideal. We've been tracking the case-sensitivity issue here: https://github.com/aspnet/MvcPrecompilation/issues/37

**Comment by i4Contractor** [comment]
As this is a duplicate issue, I am closing it.
