### ISSUE TITLE
Fix SimpleAppDesktopOnly.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/MvcPrecompilation#132]
Unblocked cross-plat builds with [this](https://github.com/aspnet/MvcPrecompilation/commit/bde6a8f20fd9ea79b7e89f9e4bd775f404c6c995) commit. Not entirely sure why it unblocks those builds though. My bet is that once we re-enable desktop tests that it doesn't actually work at runtime.

@pranavkm any ideas why this worked?

**Comment by pranavkm** [comment]
Not super sure why this commit works. We conditionally import targets (https://github.com/aspnet/MvcPrecompilation/blob/dev/build/common-testapps.props#L11), so the tfm wouldn't have been defined by the time the import is evaluated.

**Comment by NTaylorMullen** [comment]
Desktop tests are re-enabled and this seems fine.
