### ISSUE TITLE
Back port using AssemblyName instead of MSBuildProjectName fix to 1.1-* release

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/MvcPrecompilation#133]
From https://github.com/aspnet/MvcPrecompilation/issues/125.
We fixed this issue in https://github.com/aspnet/MvcPrecompilation/pull/82 for 2.0.0-preview1. We should consider back porting it to 1.1. release.

cc @Eilon @pranavkm

**Comment by bdovaz** [comment]
Yes, please.

**Comment by shbhar** [comment]
+1

**Comment by pranavkm** [comment]
@shbhar the tool targets `netstandard2.0` which works with `net462`. If you're seeing specific issues with the tool on a desktop targeting project, feel free to open a separate issue.

**Comment by Eilon** [comment]
This patch is *approved* for 1.1.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/MvcPrecompilation/commit/70aafafb0f12cd479f2aaedde236ce7be335c614
