### ISSUE TITLE
Bring back RID-specific tests, e.g. by re-enabling the net461 win7-x86 functional test

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/MvcPrecompilation#134]
With the new MvcPrecompilation testing infrastructure we have project references to our src packages. The problem with this approach is when you have an x86 test application doing the following:
```
dotnet restore
dotnet build
```

It ends up copying over the x64 src bits into the x86 directory. This of course results in a bad format exception when attempting to pre-compile a test app. @pranavkm said he'd take a look at fixing this.

**Comment by pranavkm** [comment]
We have E2E coverage for this via MusicStore. See https://github.com/aspnet/MusicStore/commit/a01bee876d4573a149d78cd90bbcbb4802e1f0c4
