### ISSUE TITLE
Question: are MVC view compiles deterministic ?

### ISSUE THREAD

**Issue by davidglassborow** [aspnet/MvcPrecompilation#141]
Roslyn can do deterministic builds (https://github.com/dotnet/roslyn/issues/372), and I've recently added this to Visual F# (https://github.com/Microsoft/visualfsharp/pull/2954).

At my workplace, this means that the MVC view compilation is the only step left in our build processes that isn't deterministic. I was wondering if the new aspnetcore view compilation will be deterministic ?, or if that is a feature you would consider adding ?

**Comment by rynowak** [comment]
No, they are not
1. We don't pass `deterministic = true` to the `CSharpCompilerOptions` - this is easy to fix
2. Each tag helper usage gets a unique identifier assigned to it, right now this isn't deterministic

**Comment by davidglassborow** [comment]
Is this something you would be happy to add ?  If so I'll have a look at a PR to do so (probably post core 2.0 release)

**Comment by rynowak** [comment]
> Is this something you would be happy to add ? If so I'll have a look at a PR to do so (probably post core 2.0 release)

If it adds value for you, and you want to send us a PR then sure we'd be happy to take it for 2.1. We already have the capability to replace the 'id generator' for tests, we'd just have to figure out a way to generate stable ids.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#1446
