### ISSUE TITLE
Move the netcoreapp2.0 runtime library into the build folder

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/MvcPrecompilation#143]
This way a users application can't actually call into ViewCompilation code.

@Eilon this should be done for RTM

**Comment by pranavkm** [comment]
Might have to check this one - if you have a `lib\net451`, but no `lib\netcoreapp2.0`, you might not be able to install the package in a netcoreapp targeting project. That said, there's no API exposed by the assembly and it's not meant to be deployed `PrivateAssets="true"`, so there's not a lot of risk of application code calling in to it.

**Comment by Eilon** [comment]
With the new PTF vs. ATF thing I don't know what the behavior would be.

**Comment by NTaylorMullen** [comment]
> With the new PTF vs. ATF thing

What's PTF vs. ATF?

**Comment by Eilon** [comment]
PackageTargetFallback vs. AssetTargetFallback.

**Comment by Eilon** [comment]
Details here: https://github.com/NuGet/Home/wiki/Enable-.NET-Core-2.0-projects-to-work-with-.NET-Framework-4.6.1-compatible-packages

**Comment by Eilon** [comment]
Not saying it's necessarily related, but it might be relevant.

**Comment by natemcmaster** [comment]
Btw, same is true of the .NET Framework assembly. These are currently packed into `runtimes/win-{x64, x86}/lib/`, which means NuGet treats this as available assemblies. Would be better to put all these console tools in a non-asset folder. Our other tooling packages put these into `tools/` or `toolsassets/` to ensure NuGet ignores them.

**Comment by NTaylorMullen** [comment]
Today we do this because we rely on the CI to auto-generate binding redirect files for those guys. We could manually create binding redirects that would work with most apps to move those bits around.

**Comment by natemcmaster** [comment]
The binding redirects can't be packed. You have to generate those based on the dependencies of the project. 

FWIW - it's more complicated, but you could "borrow" the binding redirects generated for the app, or use AppDomains to better manage assembly resolution.

**Comment by Eilon** [comment]
We need to talk to @DamianEdwards about some aspects of this because it seems like we're having to work around too many sharp edges in the system.

**Comment by pranavkm** [comment]
Binaries moved. @Eilon do you want me to keep the work item open so we can follow up with @DamianEdwards?
