### ISSUE TITLE
App expects ViewCompilation assembly after publish, but it is not present in the runtime store (2.0.0-preview2-final)

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MvcPrecompilation#146]
Using dotnet CLI 2.0.0-preview2-006484

**Repro**
Install latest .NET Core CLI: https://github.com/dotnet/cli/tree/release/2.0.0-preview2#installers-and-binaries

```ps1
# Clear caches
dotnet nuget locals all --clear
rm -r -f $env:USERPROFILE\.dotnet

# make new template app
mkdir app
cd app
dotnet new mvc

# publish and run
dotnet publish -o pub -c Release
cd pub
dotnet app.dll
```

**Result**
```
dotnet app.dll
Error:
  An assembly specified in the application dependencies manifest (app.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Razor.ViewCompilation', version: '2.0.0-preview2-final'
    path: 'lib/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-preview2-final-osx-x64.xml;aspnetcore-store-2.0.0-preview2-final-linux-x64.xml
```

cc @NTaylorMullen @Eilon @muratg @JunTaoLuo

**Comment by JunTaoLuo** [comment]
We have resolved this with https://github.com/aspnet/MetaPackages/pull/167. @NTaylorMullen is there a bug tracking the removal of the package from the store in the next release?

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/MvcPrecompilation/issues/143 is the one that will indirectly remove it from the store. Is there additional things that need to be done to ensure it gets rmeoved?

**Comment by pranavkm** [comment]
@JunTaoLuo close?

**Comment by muratg** [comment]
Yeah, let's verify with the latest bits (Links here: https://github.com/aspnet/Release/issues/144) and close.

**Comment by NTaylorMullen** [comment]
Worked for me Windows Server 2016

**Comment by natemcmaster** [comment]
Works in Docker Nano Server.

**Comment by JunTaoLuo** [comment]
Closing since it's been verified by others as well.
