### ISSUE TITLE
NetCoreApp2.0 Web App with win7-x86 RuntimeIdentifier fails on publish

### ISSUE THREAD

**Issue by bzhu94** [aspnet/MvcPrecompilation#151]
When I publish a NetCoreApp2.0 Web App (with Individual Authentication) with a win7-x64 RuntimeIdentifier, publish succeeds. However, when I change the RuntimeIdentifier to win7-x86, publish fails and gives the following error during precompilation of the Razor views: 

```
Failed to load the dll from [???], HRESULT: 0x800700C1

An error occurred while loading required library hostpolicy.dll from [C:\Users\brzh\source\repos\Core2.0WebApp\Core2.0WebApp\bin\Release\netcoreapp2.0\win7-x86\]
```

This happens even when the x86 CLI is installed. This is due to the fact that the ```_RunForCore``` target in ```Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets``` hardcodes "dotnet exec", so the dotnet.exe used will be first one found when iterating through the probing paths defined by the ```%path%``` variable. It happens that C:\Program Files\dotnet\ comes before C:\Program Files (x86)\dotnet in the default value of ```%path%```, so the x64 bits are always used. 

As a workaround, if we swapped the order of the two probing paths in %path%, publish would work fine with the x86 RuntimeIdentifier.

**Comment by pranavkm** [comment]
This is a variant of the issue described in https://github.com/aspnet/MvcPrecompilation/issues/102. 

Publishing for a rid other than the one in the current dotnet is currently broken. Here's a potential workaround for the issue: https://github.com/aspnet/MvcPrecompilation/issues/102#issuecomment-287653103.
