### ISSUE TITLE
Running precompilation tool on an Empty Web Application fails

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#162]
Repro steps

From VS,
1. File > New Project > ASP.NET Core Web Application > Empty (.NET Core) - 2.0.
2. Publish to Folder

Publishing fails with

```
EXEC(0,0): Warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
EXEC(1,11): Error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
EXEC(1,54): Error CS0518: Predefined type 'System.String' is not defined or imported
```

The deps file is missing references to `Microsoft.NETCore.App` \ `System.Runtime.dll` which causes the assembly emit to fail.

**Comment by DamianEdwards** [comment]
Eeep, that's really bad. What's the root cause you think?

**Comment by pranavkm** [comment]
This might have been fixed in the templates. The issue was that Empty Web had `PreserveCompilationContext` disabled (https://github.com/dotnet/templating/commit/34037263ab6ddfcce6b4d65507e21c168521b45e). Usually we'll print a message saying you are missing this when a view fails to compile. In the absence of any views, we only compile an auto-generated `AssemblyInfo` that fails this way. The simplest fix, IMO, is to no-op the tool if there aren't things to compile.

**Comment by mkArtakMSFT** [comment]
We're not going to make any other significant enhancements to this feature, as we'll be replacing it with a better one.

**Comment by rocklan** [comment]
This is also a problem if you create a WebApi project with no views, so I'm not sure why this issue is closed when it's still a bug.. but as a workaround, adding the following to my .csproj fixed the problem for me:

    <PropertyGroup>
        <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
        <PreserveCompilationContext>false</PreserveCompilationContext>
    </PropertyGroup>
