### ISSUE TITLE
Is possible to build PrecompiledViews.dll in the main output.dll?

### ISSUE THREAD

**Issue by CXRom** [aspnet/MvcPrecompilation#172]
I want to integrate the PrecompiledViews.dll in the same output its possible?

The scenario is multiple proyects in one solution. In this moment every partial project generate output.dll and PrecompiledViews.dll but when i add the reference project in the main its olny take the output.dll.

**Comment by pranavkm** [comment]
Not out of the box. Your easiest option would be to copy the precompiled binary as post-build step. If you do manage to get the binary merged, you'd have to add a [`ViewsFeatueProvider`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs) that knows how to discover precompiled views from the primary assembly.

**Comment by pranavkm** [comment]
Feel free to reopen this if you have further questions.
