### ISSUE TITLE
Precompilation fails when more than one _ViewImports has the same `@namespace` directive

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#174]
Consider,

```
/Views
    /_ViewImports.cshtml (`@namespace WebApp`)
    /_ViewStart.cshtml
/Pages
    /_ViewImports.cshtml (`@namespace WebApp`)
    /_ViewStart.cshtml
```

Both `_ViewStarts` would be generated with the same fully qualified type name. This works at runtime because the two types are in distinct assemblies but fails for precompilation because we compile them in to one assembly.

**Comment by pranavkm** [comment]
@rynowak do you recall why we chose not to mangle the type name when we added the `@namespace` feature? Is mangling the type name a possible solution here? The alternative to this would be to mirror what we do at runtime and produce an assembly per view, but that doesn't seem like a very good solution.

**Comment by rynowak** [comment]
Mangling the names would be a good solution, at least for viewstarts.

**Comment by ctolkien** [comment]
Just hit this with a MVC `Area` with it's own `_ViewImports`.

**Comment by pranavkm** [comment]
@ctolkien until we fix this, picking a different namespace is the way to go.

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Razor#1811
