### ISSUE TITLE
What is the difference between BuildAction = EmbeddedResource & MvcPrecompilation?

### ISSUE THREAD

**Issue by devtrix** [aspnet/MvcPrecompilation#181]
Could someone kindly explain the difference please.  
Raj

**Comment by pranavkm** [comment]
`BuildAction=EmbeddedResource` lets you create a file provider over embedded resources. Views are compiled at runtime just as with files on disk. MvcPrecompilation lets you compile views as part of your build or publish pipeline. Consequently issues in compilation will show up as part of your build pipeline and you aren't paying the costs of runtime compilation. Additionally precompiled views is a better fidelity source compared to the embedded file provider <sup>[1](https://github.com/aspnet/FileSystem/issues/184) [2](https://github.com/aspnet/Mvc/issues/6489)</sup>

**Comment by pranavkm** [comment]
Feel tree to reopen if you have further questions.
