### ISSUE TITLE
Build fails when MvcRazorCompileOnPublish is true

### ISSUE THREAD

**Issue by martincostello** [aspnet/MvcPrecompilation#185]
I have updated an existing ASP.NET Core MVC application from `1.1.2` to `2.0.0`, and everything has worked fine with the upgrade except that the build fails is view pre-compilation is enabled.

Disabling it by setting the `MvcRazorCompileOnPublish` MSBuild property to `false` fixes the build, which has been observed to fail in Visual Studio 2017 15.3, and via `dotnet build` on [Windows](https://ci.appveyor.com/project/martincostello/website/build/1.0.379#L362) and [Linux](https://travis-ci.org/martincostello/website/builds/264506897#L1020).

The build fails with one of the following errors:

**[AppVeyor build](https://ci.appveyor.com/project/martincostello/website/build/1.0.379)**
```ps
C:\Users\appveyor\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""C:\projects\website\.dotnetcli\dotnet.exe" exec --runtimeconfig "C:\projects\website\src\Website\bin\Release\netcoreapp2.0\Website.runtimeconfig.json" --depsfile "C:\projects\website\src\Website\bin\Release\netcoreapp2.0\Website.deps.json" "C:\Users\appveyor\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450751. [C:\projects\website\src\Website\Website.csproj]
dotnet publish failed with exit code 1
```

**[Travis build](https://travis-ci.org/martincostello/website/builds/264506897)**
```sh
/home/travis/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""/home/travis/build/martincostello/website/.dotnetcli/dotnet" exec --runtimeconfig "/home/travis/build/martincostello/website/src/Website/bin/Release/netcoreapp2.0/Website.runtimeconfig.json" --depsfile "/home/travis/build/martincostello/website/src/Website/bin/Release/netcoreapp2.0/Website.deps.json" "/home/travis/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj/Release/netcoreapp2.0/microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 129. [/home/travis/build/martincostello/website/src/Website/Website.csproj]
```

To replicate, clone the `AspNet-Core-2.0.0-Precompilation-Fails` branch of `https://github.com/martincostello/website` and run either:
  * `Build.ps1 -RestorePackages` or
  * `build.sh --restore-packages`.

**Comment by pranavkm** [comment]
@martincostello the line `<Target Name="AddGeneratedContentItems" BeforeTargets="AssignTargetPaths" DependsOnTargets="PrepareForPublish">` in your csproj moves the publish step to a target that runs before `Compile`. Removing the `DependsOnTargets` fixed the issue although I'm not entirely sure what the significance of invoking the target that early is. If you'd like to preserve the current pipeline as is, I'd recommend, setting `MvcRazorCompileOnPublish` followed by invoking the `MvcRazorCompile` target prior to `PublishOnly`. I haven't verified it, but I think this should work.

**Comment by martincostello** [comment]
@pranavkm Thanks - removing `DependsOnTargets` fixed it. This target is there to work around the `1.x.x` SDK not copying all files into the published directory, which was in a GitHub comment somewhere in a GitHub issue as a workaround and I'd just copied verbatim.
