### ISSUE TITLE
Consider adding a switch to remove the refs directory produced as part of the publish output

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#20]
Precompilation relies on `preserveCompilationContext` to produce a deps file with enough information to compile views. This is identical to how runtime compilation works. One side effect of having this flag is that additional references binaries get copied to a `refs` directory under the publish directory. If the application performs no runtime compilation, these binaries are not required.

We could optionally remove these binaries once precompilation completes.

**Comment by Eilon** [comment]
This sounds like it's a separate decision from precompilation so it shouldn't be combined within the precompilation tool. That is, it makes more sense it just another step in the targets of the project that after calling precompilation optionally goes and deletes another folder.
