### ISSUE TITLE
Precompiled views does not run with Areas folder in project and library in 2.0.0 

### ISSUE THREAD

**Issue by Smilefounder** [aspnet/MvcPrecompilation#202]
I think my team are facing an issue with precompiled views does not run with Areas folder in project and library in 2.0.0.

Is it support with Areas folder structure yet?

**Comment by pranavkm** [comment]
@Smilefounder area views should work just as any other view. Do you have a repro sample where precompilation doesn't work? Would be helpful to diagnose if there is in fact a bug.

**Comment by Smilefounder** [comment]
@pranavkm : Actually my team is working on the project for the client that I can not provide the source code, will provide you with some sample source code later ASAP. For now you can see the error message below:

![image](https://user-images.githubusercontent.com/3785721/30575148-07635112-9d29-11e7-9283-654d8dfa323a.png)

**Comment by rynowak** [comment]
What about the `csproj`? Is there anything in there related to .cshtml files?

**Comment by Smilefounder** [comment]
@rynowak : My team did check the csproj. But there are nothing wrong with csproj. That is the reason why I'm a bit concern that "MvcPrecompilation" not work with the following structure:

![image](https://user-images.githubusercontent.com/3785721/30576091-8e69ea30-9d2f-11e7-9a27-f0ed1cca7f0c.png)

**Comment by pranavkm** [comment]
Thanks, I'll give the sample a try.

**Comment by pranavkm** [comment]
@Eilon self assigning for investigation.

**Comment by Smilefounder** [comment]
@pranavkm : Thanks. Feel free to let me know if you have any concern.

**Comment by nhathoang989** [comment]
I think we can fix this issue manually by edit .csproj:

- Prevent precompiled (optional)
 `<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
  </PropertyGroup>
`
- Include views
 `<ItemGroup><Content Include="Views\**\*" CopyToPublishDirectory="Always" /><Content Include="Areas\*\Views\**\*" CopyToPublishDirectory="Always" /></ItemGroup>`

**Comment by pranavkm** [comment]
@Smilefounder I tried your app. The route you describe in the error (`Portal/Article/Index`) does not exist in the application. I used a different area route (`Portal/Contents/Add-article`) and I was able to successfully get a view to be returned with 1.1 and 2.0 after publish without removing view compilation. Is there a specific view that isn't being rendered?

**Comment by Smilefounder** [comment]
Thanks @pranavkm. Let me and the team try again. Look like our source code need to be clean up as it is from .net core v1.1. Please feel free to close this issue.

**Comment by pranavkm** [comment]
Cool. Reopen this issue if you continue seeing this issue.
