### ISSUE TITLE
How avoid "PrecompiledViews.pdb" in publish dir?

### ISSUE THREAD

**Issue by ahdung** [aspnet/MvcPrecompilation#204]
VS2017, dotnet core 2.0, publishing with Release mode.

I can add `<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>` in release.pubxml to avoid all *.pdb except "xx.PrecompiledViews.pdb", please help.

**Comment by pranavkm** [comment]
Spoke to @vijayrkn offline. We'll need to honor the `CopyBuildOutputToPublishDirectory` to do this: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Publish.targets#L198-L202.

@ahdung unfortunately we don't have a good way to disable publishing symbols at this point. Your best bet would be to run a build target after publish and delete the file from the output directory.

**Comment by vijayrkn** [comment]
@pranavkm The property is `CopyOutputSymbolsToPublishDirectory`

**Comment by ahdung** [comment]
@vijayrkn I know and using this tag, but it not work for xx.PrecompiledViews.pdb.

**Comment by vijayrkn** [comment]
>@ahdung unfortunately we don't have a good way to disable publishing symbols at this point. Your best bet would be to run a build target after publish and delete the file from the output directory.

I believe @pranavkm will be adding code to honor this property.
