### ISSUE TITLE
Types implemeting IDesignTimeMvcBuilderConfiguration can't be loaded if they do not have a no-arg constructor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#207]
The pattern we've been recommending users to allow configuring `IMvcBuilder` is to make the Startup type implement `IDesignTimeMvcBuilderConfiguration` and move the configuration of `IMvcBuilder` in to `IDesignTimeMvcBuilderConfiguration.ConfigureMvc`:

```C#
public class Startup : IDesignTimeMvcBuilderConfiguration
{
    public void ConfigureMvc(IMvcBuilder builder) { ... }

    public void Configure(IServiceCollection serviceCollection)
    {
        var builder = serviceCollection.AddMvc();
        ConfigureMvc(builder);
        ...
    }
}
```

The tool assumes that the type has an empty constructor (it does `Activator.CreateInstance`). This doesn't work with the Startup generated from our 2.0.0 templates - it has a ctor that accepts a `IConfiguration` argument.

**Comment by pranavkm** [comment]
One workaround would be to have not-Startup implement the interface:

```C#
public class Startup
{
     public void Configure(IServiceCollection serviceCollection)
    {
        var builder = serviceCollection.AddMvc();
        new MvcConfiguration().ConfigureMvc(builder);
        ...
    }
}

public class MvcConfiguration : IDesignTimeMvcBuilderConfiguration
{
     public void ConfigureMvc(IMvcBuilder builder) { ... }
}
```

**Comment by pranavkm** [comment]
Yup. The right fix seems to do most of the work we do in WebHostBuilder (https://github.com/aspnet/Hosting/blob/500668619fc790c43ccbb5ab399bdbbcf3955414/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L243-L262) or something along these lines.

**Comment by Eilon** [comment]
Moving to backlog until we get more feedback on this.

**Comment by mkArtakMSFT** [comment]
We're not going to make any other significant enhancements to this feature, as we'll be replacing it with a better one.
