### ISSUE TITLE
Is there any that we can make MVC precompile on runtime?

### ISSUE THREAD

**Issue by Smilefounder** [aspnet/MvcPrecompilation#209]
Hi team,

It is nice that we have MVC precompile option.
But my team now facing an issue that we would like to precompile VMC view on runtime. Is it possible yet?

Thanks,
Huy

**Comment by pranavkm** [comment]
You can disable precompilation `<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>` and views will get published and runtime compiled. Is that what you meant to ask?

**Comment by Smilefounder** [comment]
@pranavkm : Sorry for have you confused. I asked the question because our Swastika I/O going to have online view editing from the CMS. But I still want to have this function turn on and compile the updated view after all. Is it possible?

**Comment by pranavkm** [comment]
Mvc does not currently support precompiled updateable views. We had an offline discussion about this, but haven't as yet fleshed out an actual feature design for it. cc @rynowak \ @DamianEdwards

**Comment by Smilefounder** [comment]
Thanks for letting me know. This feature will be really nice to have. Hope this will come soon in the next couple versions. Else, we have to disable Precompile in our project for now.

Thanks.

**Comment by mkArtakMSFT** [comment]
This is going to be covered by the following issue: https://github.com/aspnet/Razor/issues/1809
