### ISSUE TITLE
Timeline for pre-release versions on NuGet

### ISSUE THREAD

**Issue by NickAb** [aspnet/MvcPrecompilation#21]
Hello,

Are there any chances to see this packaged on NuGet as pre-release? Are there any time-frames for that or we will have to wait for Q1/Q2 2017 release?

**Comment by rynowak** [comment]
This package is available now on MyGet, but that will require using 1.1.0 nightlies of everything.... https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Mvc.Razor.Precompilation.Tools

Perhaps @DamianEdwards or @danroth27 would like to comment on our timelines for preview release?

**Comment by DamianEdwards** [comment]
We're currently targeting a pre-release of this on NuGet for this month, and an RTM a month or so later. Of course, "targeting" doesn't not constitute an announcement or promise :smile:
