### ISSUE TITLE
Precompilation should not run on projects without views

### ISSUE THREAD

**Issue by dasMulli** [aspnet/MvcPrecompilation#211]
As optimization: If a project has no views `.cshtml`, it should not run precompilation to generate a `*.PrecompiledViews.dll`.

This makes sense for API-only apps (REST endpoints, new SignalR / ASP.NET Core Sockets).

Seen on StackOverflow: https://stackoverflow.com/questions/46700399/deleting-precompiledviews-dll-from-asp-net-core-2-api

**Comment by pranavkm** [comment]
Sounds good. There's a related issue where if you start with an application that decidedly turns off `PreserveCompilationContext` if it requires runtime compilation, it causes the tool to fail - https://github.com/aspnet/MvcPrecompilation/issues/162

**Comment by mkArtakMSFT** [comment]
We're not going to make any other significant enhancements to this feature, as we'll be replacing it with a better one.
