### ISSUE TITLE
Class library view precompilation by default

### ISSUE THREAD

**Issue by svallis** [aspnet/MvcPrecompilation#213]
The experience when precompiling views in class libraries is currently somewhat error-prone, messy, and poorly documented (see #187). It feels to me like, especially seeing as view precompilation is turned on by default for the main project, it should also be enabled for class libraries out of the box. Turning off view precompilation anywhere should be the extraordinary case. This would bring some consistency, hopefully remove all of the noise from `csproj` files, and produce the output the vast majority of users would expect from published output.

**Comment by mkArtakMSFT** [comment]
Dup of https://github.com/aspnet/Razor/issues/1809
