### ISSUE TITLE
Consider using WebHostBuilderFactory in precompilation

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#217]
MvcPrecompilation looks for a type implementing `IDesignTimeMvcBuilderConfiguration` in the application's assembly and uses it to configure an `IMvcBuilder` if present. In the absence of this interface, the tool setups a vanilla MvcBuilder (essentially one that we get from `app.AddMvc()`) and runs compilation using services created here. The initial goal of the `IDesignTimeMvcBuilderConfiguration` type was to avoid running too much startup code and failing. However, given that running startup discovery is staple to `dotnet-ef` and Mvc's test infrastructure, it seems like it would be good to bring precompilation in line with this. The proposal here is to

1. Use the current code path if the application has a type that implements `IDesignTimeMvcBuilderConfiguration`
2. Use WebHostBuilderFactory discovery otherwise.

**Comment by Eilon** [comment]
Is this needed anymore, given that we're going the RZC route?

cc @rynowak @DamianEdwards

**Comment by rynowak** [comment]
Deffo not needed

**Comment by mkArtakMSFT** [comment]
We're not going to make any other significant enhancements to this feature, as we'll be replacing it with a better one.
