### ISSUE TITLE
Flaky test: Precompilation_PreventsRefAssembliesFromBeingPublished

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MvcPrecompilation#224]
There seems to be some contention on the testapp dll's in [these](http://aspnetci/viewLog.html?buildId=363359&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId-1193754046721736950) tests, likely exposed by tests running in parallel.

**Comment by mkArtakMSFT** [comment]
@pranavkm , can you please have a look at this? Thanks!

**Comment by pranavkm** [comment]
Test skipped as part of https://github.com/aspnet/MvcPrecompilation/commit/62819b4abc94bafbf090387c62fb3fbcca07e0ca
