### ISSUE TITLE
How to exclude certain views from being precompiled

### ISSUE THREAD

**Issue by joshua-mng** [aspnet/MvcPrecompilation#226]
I have certain view files (plugin and email razor files) which I want to exclude when publishing.

Can you tell me how to do that?

**Comment by mkArtakMSFT** [comment]
@pranavkm , can you please advise here? Thanks!

**Comment by pranavkm** [comment]
We look at all `Content` items that have a cshtml extension. Consequently, excluding a file from the csproj (Right click -> Exclude from project) should exclude the file from precompilation. Alternatively, there's a `MvcRazorFilesToCompile` that gives you full fidelity on the ItemGroup you can want to compile:

```xml
<Project>
<ItemGroup>
   <MvcRazorFilesToCompile Include="..." />
</ItemGroup>
</Project>
```

**Comment by joshua-mng** [comment]
Here is the snipped of code I'm using

When I exclude using `<Content Remove="Plugins\**" />`, those views are not being copied into the publish output. I want them to be copied to the publish output directory.

When I also use MvcRazorFilesToCompile, views inside Plugins directory are still being compiled.

My application has the following structure:

```
ROOT/
  Plugins/
  Themes/
```

Plugins directory contains plugin DLL, views, assets, at startup, plugin manage scans the directory and shadow copy all plugin DLL files into temporary directory and loads them dynamically.
So that means, views inside this Plugins/ directory references models which are only available at runtime.
So precompilation at build them chokes on model not found error. So what I want is

- Exclude all view files in Plugins/ directory to be excluded from precompilation
- But I want them to be still copied to the publish output directory when I publish (without compilation)

I tried to use MvcRazorFilesToCompile like following;
`<MvcRazorFilesToCompile Remove="Plugins\**" />`

But still it's not working, I'm guessing it gets populated from the Content items later or so.

So please guide me what I have to do to achieve what I want (like mentioned above)

Thank you very much

```
<Compile Remove="Plugins\**" />
<EmbeddedResource Remove="Plugins\**" />
<None Remove="Plugins\**" />
<Content Remove="Plugins\**" />
<Content Include="Plugins\**" CopyToPublishDirectory="PreserveNewest" Exclude="Plugins\**\*.config;Plugins\**\*.cshtml;Plugins\**\*.json" />
		<Content Include="Themes\**" CopyToPublishDirectory="PreserveNewest" Exclude="Themes\**\*.config;Themes\**\*.cshtml;Themes\**\*.json" />
```

**Comment by joshua-mng** [comment]
So what you suggest is to do following in order to achieve what I want:

```
<PropertyGroup>
    <MvcRazorExcludeViewFilesFromPublish>false</MvcRazorExcludeViewFilesFromPublish>
</PropertyGroup>

<ItemGroup>
    <MvcRazorFilesToCompile Include="*.cshtml" Exclude="Plugins\**"\*.cshtml />
</ItemGroup>
```

I tried above, and it STILL compiles all view files inside Plugins folder.

Can you paste snippet of code to do following?

- I want all CSHTML files to be precompiled upon publish
- But I DON'T want views inside Plugins folder to be precompiled, but still to be copied to the publish output

Thank you

**Comment by pranavkm** [comment]
`*.cshtml` would only find views at the top level it will not intersect with any files in the Plugins directory. You probably want something along the lines of
*  `Views\**\*.cshtml` or
* `**\*.cshtml` while additionally excluding files under the `bin` and `obj` directory.  

If you're still running in to trouble, could you include a sample and we go from there?

**Comment by joshua-mng** [comment]
Thanks

It seems following line did the trick.

`<MvcRazorFilesToCompile Include="**\*.cshtml" Exclude="Plugins\**\*.cshtml;Themes\**\*.cshtml;bin\**\*.cshtml;obj\**\*.cshtml" />`

**Comment by benmccallum** [comment]
Sorry to be a pain, and I know this isn't the best place to ask, but is there a way to do this exclusion for MVC 5 projects? There's lots of information on the `<MvcBuildViews>true</MvcBuildViews>` setting, but nothing about being able to prevent certain .cshtml files from being pre-compiled.

We use a handful of .cshtml files at runtime to generate emails, so I need these to be deployed but everything else I want pre-compiled so I can have more assurance they won't have any runtime compilation issues.

Have searched around the net but can't find anything thus far.

Thanks!
