### ISSUE TITLE
Come up with Razor compilation change story for transition from 2.0 to 2.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#230]
We want to guide users to use Razor.Design. We should print a warning when the target is invoked but continue functioning as before.

**Comment by mkArtakMSFT** [comment]
Moving to preview2, as we still have no story for transitioning (including whether we will have a warning message or not)

**Comment by pranavkm** [comment]
cc @rynowak 

The Sdk handles the transition for you - the only thing left to do is possibly add a message that tells users to use RazorSdk if `MvcRazorCompile` is invoked.

**Comment by pranavkm** [comment]
Spoke to @rynowak offline and we don't need to do anything additional here.
