### ISSUE TITLE
compilation fails for: platform AnyCPU, .netframework

### ISSUE THREAD

**Issue by yepeekai** [aspnet/MvcPrecompilation#240]
The targets file doesn't support AnyCPU when using the .netframework.

Here is the problematic portion in the [file](https://github.com/aspnet/MvcPrecompilation/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets)

`    <PropertyGroup Condition="'$(_MvcViewCompilationBinaryPath)'==''">
      <_MvcViewCompilationBinaryPath Condition="'$(PlatformTarget)'=='x64'">$(MSBuildThisFileDirectory)$(MSBuildThisFileName)-x64.exe</_MvcViewCompilationBinaryPath>
      <_MvcViewCompilationBinaryPath Condition="'$(PlatformTarget)'=='x86'">$(MSBuildThisFileDirectory)$(MSBuildThisFileName)-x86.exe</_MvcViewCompilationBinaryPath>
    </PropertyGroup>
`

There should be a third entry for AnyCPU that select one of the 2 files (x64 or x86).  I personally don't have a preference, but maybe it should follow the 'prefer 32 bits' flag if present

**Comment by mkArtakMSFT** [comment]
Thank you for your feedback.
@rynowak, any thoughts about this one?

**Comment by rynowak** [comment]
@pranavkm knows this area, I'm not very familiar with it

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Yup, seems about right. We have precedence to use 64 bit binaries for AnyCPU (https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/dotnet-ef/RootCommand.cs#L118-L120), so presumably we'd need to do fix up the target to do this. @mkArtakMSFT how should I proceed with this issue? The fix is trivial, but likely more useful in a patch scenario rather than 2.1.0 where you'd use Razor Sdk.

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm. @yepeekai, I'm trying to evaluate the urgency of this, so would be great to understand how critical is the impact of this for you?

**Comment by yepeekai** [comment]
I put a workaround in my csproj file (a target before and after the one here) so there is no urgency in my case.  thanks.

**Comment by pranavkm** [comment]
This is affecting our F# template tests (https://github.com/aspnet/templating/issues/365). Getting this addressed for preview2.
