### ISSUE TITLE
Is it possibile to both precompile and still publish cshtml files ?

### ISSUE THREAD

**Issue by valeriob** [aspnet/MvcPrecompilation#243]
if i enable view precompilation and set this property on the project file <MvcRazorExcludeViewFilesFromPublish>false</MvcRazorExcludeViewFilesFromPublish>
will i benefit from view pre-compilation on first startup if i do not modify those files ?

**Comment by mkArtakMSFT** [comment]
Hi @valeriob. There is no way to have both precompilation and runtime compilation running side by side. Those are mutually exclusive by design. In ASP.NET Core 2.1, however, we are going to support both compiling the views and allowing runtime updates for those.

**Comment by kmanpro** [comment]
Has this been implemented with the 2.1 release? I didn't see it anywhere on the release notes?
