### ISSUE TITLE
Rename this project to Razor ViewCompilation

### ISSUE THREAD

**Issue by rynowak** [aspnet/MvcPrecompilation#25]
We should rename this to View Compiler/View Compilation

**Comment by Eilon** [comment]
Rename this to: `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.*`.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/MvcPrecompilation/commit/bfdd939e26db59cc451a099d38514d4a7dd73315
