### ISSUE TITLE
How to generate multiple projects？

### ISSUE THREAD

**Issue by cqkisyouq** [aspnet/MvcPrecompilation#260]
I have a main project  "A"
Referencing project B
A contains Views
B contains Views
How can I publish it together?

Now there is only one "A.precompiledviews.dll" that has been released without "B.precompiledviews.dll".

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @cqkisyouq.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
There isn't first class support for precompiled views built using the precompilation tool to be used in project references or packaged. We're addressing these deficiencies as part of the Razor SDK in 2.1.0-preview2 (See https://github.com/aspnet/Razor/issues/1740). 

That said, here's how you you could edit your project A to invoke the `MvcRazorCompile` target and copy the precompiled views dll over. https://github.com/aspnet/MvcPrecompilation/blob/release/2.0/testapps/ApplicationUsingPrecompiledViewClassLibrary/ApplicationUsingPrecompiledViewClassLibrary.csproj#L19-L27 Has a snippet for what this would look like.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
