### ISSUE TITLE
precompiling views which are in separate project

### ISSUE THREAD

**Issue by guylando** [aspnet/MvcPrecompilation#268]
I would like to perform views precompilation in the following scenario for net core version 2.1.0-rtm-30733 targeting net461:

Solution has 2 projects:
Project A has the startup.cs class and all the logic
Project B has wwwroot and Views

project A loads project B views using:
.AddRazorOptions(options =>
                {
                    options.FileProviders.Clear();
                    options.FileProviders.Add(new PhysicalFileProvider(path to views parent folder));
                })

In this scenario in which of the projects should I add the Microsoft.AspNetCore.Mvc.Razor.ViewCompilation package and MvcRazorCompileOnPublish property and after adding it, it should work without any other changes even though its in different project?

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Mvc#7759
