### ISSUE TITLE
Precompilation does not work for applications using relative path

### ISSUE THREAD

**Issue by gdau** [aspnet/MvcPrecompilation#27]
I have structured my ASP.NET Core project according to "Feature Slices" as outlined here:

[https://msdn.microsoft.com/en-us/magazine/mt763233.aspx](https://msdn.microsoft.com/en-us/magazine/mt763233.aspx)

The result is that the views are stored alongside the relevant models and controllers (and not in the "Views" folder). The _Layout file is stored at "Features/Shared/_Layout.cshtml".

When I run the site from Visual Studio or publish the site without razor precompilation enabled, the site works fine. When I enable precompilation I get an error in the console:

```
The layout view 'Shared/_Layout.cshtml' could not be located. The following locations were searched:
Shared/_Layout.cshtml
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)

```
I have changed the publish options to output the relevant cshtml files so they definitely are included in the publish destination even though I know this technically isn't required when using precompilation (this is also verified since the site works fine without the precompilation enabled).

Is having an alternate location for the Views supported in the precompilation scenario?

**Comment by pranavkm** [comment]
Discussed here - https://github.com/aspnet/Mvc/issues/5508#issuecomment-260072552

The issue has to do with the view engine expecting paths with forward slashes. However, the View metadata that is generated contains paths with back-slashes. The actual issue might require looking in to `RazorViewEngine` \ `CompilerCache`, but for this release we can make a simple fix by normalizing the path casing in the metadata.

**Comment by pranavkm** [comment]
@Eilon follow up - https://github.com/aspnet/MvcPrecompilation/issues/33 which we probably don't want to take for this release.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/MvcPrecompilation/pull/65
