### ISSUE TITLE
--runtime didn't work, while -r does

### ISSUE THREAD

**Issue by livarcocc** [aspnet/MvcPrecompilation#276]
_From @sebastienros on June 9, 2018 18:13_

I managed to do `--self-contained -r win-x64` but `--self-contained --runtime win-x64` fails stating I either need to no use `--self-contained` or specify a runtime id.

Full command:
`dotnet publish -c Release -o c:\temp\publish5 --self-contained --runtime win-x64`

Error message:
```
C:\Users\sebros\AppData\Local\Microsoft\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. 
```

SDK 2.1.300

_Copied from original issue: dotnet/cli#9452_

**Comment by livarcocc** [comment]
_From @peterhuene on June 11, 2018 22:25_

Hi @sebastienros.  I'm unable to reproduce this on Windows or macOS with 2.1.300.  The `--runtime` option is being respected properly by the `publish` command.

Could you provide a full repro that demonstrates the problem?  Thanks!

**Comment by livarcocc** [comment]
_From @sebastienros on June 11, 2018 23:24_

```
PS C:\temp> cd \temp
PS C:\temp> git clone https://github.com/OrchardCMS/OrchardCore
Cloning into 'OrchardCore'...
remote: Counting objects: 49469, done.
remote: Total 49469 (delta 0), reused 0 (delta 0), pack-reused 49468
Receiving objects: 100% (49469/49469), 33.85 MiB | 27.25 MiB/s, done.
Resolving deltas: 100% (35186/35186), done.
Checking out files: 100% (3144/3144), done.
PS C:\temp> cd .\OrchardCore\
PS C:\temp\OrchardCore> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba
...
PS C:\temp\OrchardCore> cd .\src\OrchardCore.Cms.Web\
dotnet publish -c Release -o c:\temp\publish5 --self-contained --runtime win-x64
...
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. [C:\temp\OrchardCore\src\OrchardCore.Cms.Web\OrchardCore.Cms.Web.csproj]
PS C:\temp\OrchardCore> cd .\src\OrchardCore.Cms.Web\
dotnet publish -c Release -o c:\temp\publish5 --self-contained --runtime "win-x64"
...
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. 
```

Note that `dotnet publish -c Release -o c:\temp\publish5 --runtime win-x64` without `--self-contained` worked in that case.

I am on Skype for Business if you want to see it for yourself.

**Comment by livarcocc** [comment]
_From @peterhuene on June 12, 2018 3:52_

I was able to reproduce it with `OrchardCore.Cms.Web`.  I'll see if I can determine the problem.

**Comment by livarcocc** [comment]
_From @peterhuene on June 12, 2018 4:12_

It looks like Razor is building the project again with an empty `RuntimeIdentifier`:

https://github.com/aspnet/MvcPrecompilation/blob/94e0ecca732e3eb9bbe9094d3db6c356e65d2f36/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets#L74

@rynowak thoughts on this?

**Comment by livarcocc** [comment]
_From @rynowak on June 12, 2018 4:28_

@sebastienros is this Razor SDK or MvcPrecompilation? Let's sync up tomorrow if it's not clear.

**Comment by livarcocc** [comment]
_From @sebastienros on June 12, 2018 5:8_

It looks like it's missing the `$(RuntimeIdentifier)` that it's checking right before the line you pointed to. But I am not an expert, so I'll check with the team tomorrow.

**Comment by livarcocc** [comment]
_From @rynowak on June 12, 2018 5:26_

Ah, I guess I didn't read the comment from @peterhuene - omitting the RID is SUPER intentional. MVC precompilation has significant limitations for apps with RIDs. @pranavkm can explain. Let's get together tomorrow and find a solution.

**Comment by livarcocc** [comment]
@rynowak Should we move this issue over to Razor?

**Comment by livarcocc** [comment]
_From @pranavkm on June 13, 2018 17:34_

Sure. Could you move it to https://github.com/aspnet/MvcPrecompilation?

**Comment by mkArtakMSFT** [comment]
We're closing this issue as MvcPrecompilation is deprecated. Consider using build-time compilation instead.
