### ISSUE TITLE
Test failure: Precompilation_WorksForIndexPage_UsingFileName

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MvcPrecompilation#285]
This test [fails](http://aspnetci/viewLog.html?buildId=534361&buildTypeId=Releases_21Public_OsxUniverse) occasionally with the following error:
```
System.Exception : Command exited unexpectedly with exit code: 134
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.StartSelfHostAsync(Uri hintUrl)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync()
   at FunctionalTests.ApplicationTestFixture.CreateDeploymentAsync(ILoggerFactory loggerFactory) in /_/test/FunctionalTests/Infrastructure/ApplicationTestFixture.cs:line 109
   at FunctionalTests.RazorPagesAppTest_CoreCLR.Precompilation_WorksForIndexPage_UsingFileName() in /_/test/FunctionalTests/CoreCLRTests/RazorPagesAppTest_CoreCLR.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-08-17T17:53:08] TestLifetime Information: Starting test Precompilation_WorksForIndexPage_UsingFileName
| [2018-08-17T17:53:08] TestLifetime Information: Starting test Precompilation_WorksForIndexPage_UsingFileName
| [2018-08-17T17:53:08] TestLifetime Information: Finished test Precompilation_WorksForIndexPage_UsingFileName in 0.000709s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Precompilation_WorksForIndexPage_UsingFolderName [failed with about the same error](http://aspnetci/viewLog.html?buildId=534361&buildTypeId=Releases_21Public_OsxUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, is this happening only for the codebase in `release/2.1` branch?

**Comment by ryanbrandenburg** [comment]
Anything with the label `Branch:2.1` is happening on the `release/2.1` branch.

**Comment by pranavkm** [comment]
Tests skipped in https://github.com/aspnet/MvcPrecompilation/commit/64b65b6991b61451ac93ce94bb43d94097c891f9
