### ISSUE TITLE
Using precompiled views

### ISSUE THREAD

**Issue by olegsavelos** [aspnet/MvcPrecompilation#288]
Hi.

I am trying to achieve a simple modularity in my .NET 4.6 app with MVC Core 2.1.
I am using the MVCBuileder.AddApplicationPart to add module assemblies and for most of it all works as expected.

My only problem is that with current setup only views that are present in the module folder are used.
Precompiled views are never searched although i have loaded them to app domain with Assembly.LoadFile

Is there any special handling needed for loading and discovery of the view.dll files ?

Here is what i am currently doing 

```
  foreach (var PLUGIN in PLUGIN_FILES)
                    {
                        try
                        {
                            Assembly PLUGIN_ASSEMBLY = null;
                            try
                            {
                                PLUGIN_ASSEMBLY = Assembly.LoadFile(PLUGIN.PluginFileName);
                                var VIEW_ASSEMBLY = Assembly.LoadFile(PLUGIN.PluginViewsFileName);
                            }
                            catch (FileLoadException)
                            {
                                throw;
                            }

                            MVC_BUILDER.AddApplicationPart(PLUGIN_ASSEMBLY);

                            MVC_BUILDER.AddRazorOptions(o =>
                            {
                                //this allows view discovery in module folder
                                o.FileProviders.Add(new PhysicalFileProvider(PLUGIN.BasePath));
                            });
                        }
                        catch (Exception ex)
                        {
                            Service.Current.LogAddError($"Could not load web module {PLUGIN.PluginFileName}", ex, SharedLib.LogCategories.Generic);
                        }
                    }
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by pranavkm** [comment]
@olegsavelos here's an example of what it would look like: https://github.com/pranavkm/PluginApp/blob/master/MainApp/Startup.cs#L71-L90

**Comment by olegsavelos** [comment]
Thanks a lot for the tip! It worked :)
