### ISSUE TITLE
Test failure: Precompilation_RunsConfiguredCompilationCallbacks

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/MvcPrecompilation#293]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=570536&buildTypeId=Releases_21Public_HighSierraOsxUniverse) with the following error:

```
System.Exception : Command exited unexpectedly with exit code: 134
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.StartSelfHostAsync(Uri hintUrl)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync()
   at FunctionalTests.ApplicationTestFixture.CreateDeploymentAsync(ILoggerFactory loggerFactory) in /_/test/FunctionalTests/Infrastructure/ApplicationTestFixture.cs:line 109
   at FunctionalTests.ApplicationWithConfigureMvcTest_CoreCLR.Precompilation_RunsConfiguredCompilationCallbacks() in /_/test/FunctionalTests/CoreCLRTests/ApplicationWithConfigureMvcTest_CoreCLR.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-10-05T14:12:51] TestLifetime Information: Starting test Precompilation_RunsConfiguredCompilationCallbacks
| [2018-10-05T14:12:51] TestLifetime Information: Starting test Precompilation_RunsConfiguredCompilationCallbacks
| [2018-10-05T14:12:51] TestLifetime Information: Finished test Precompilation_RunsConfiguredCompilationCallbacks in 0.000745s
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @Eilon (because the bot doesn't know who else to pick)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
@mkArtakMSFT can you assign?

cc @pranavkm

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 2 failures [with about the same error](http://aspnetci/viewLog.html?buildId=573386&buildTypeId=Releases_21Public_OsxUniverse) on 2.1 at 9:50:56 AM:
- Precompilation_WorksForViewsUsingDirectoryTraversal
- Precompilation_WorksForViewsUsingRelativePath

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 2 failures [with about the same error](http://aspnetci/viewLog.html?buildId=577484&buildTypeId=Releases_21Public_HighSierraOsxUniverse) on 2.1 at 1:46:15 AM:
- Precompilation_WorksForViewsUsingRelativePath
- Precompilation_WorksForViewsUsingDirectoryTraversal

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=580215&buildTypeId=Releases_21Public_OsxUniverse) on 2.1 at 4:52:49 PM:
- Publish_UsesRazorSDK

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 2 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588424&buildTypeId=Releases_21Public_HighSierraOsxUniverse) on 2.1 at 6:23:11 PM:
- Precompilation_UsesConfiguredParseOptions
- Precompilation_RunsConfiguredCompilationCallbacks

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/MvcPrecompilation/pull/298
