### ISSUE TITLE
Test failure: RunClientTests

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/MvcPrecompilation#294]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=576648&buildTypeId=Releases_22xPublic_UbuntuUniverse) with the following error:

```
FunctionalTests.Assert+ProcessAssertException : npm test exited with 1.
> @ test /mnt/work/33bdfc1cae7b2a38/modules/CORS/test/FunctionalTests
> jest
FAIL ./test.js
  ● Test suite failed to run
    TypeError: Cannot read property 'close' of undefined
      21 | 
      22 | afterAll(async () => {
    > 23 |     await browser.close();
         |                   ^
      24 | });
      25 | 
      26 | describe('CORS allowed origin tests ', () => {
      at Object.close (test.js:23:19)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.07s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
   at FunctionalTests.Assert.Success(ProcessResult& processResult) in /_/test/FunctionalTests/Assert.cs:line 17
   at FunctionalTests.CorsMiddlewareFunctionalTests.RunClientTests() in /_/test/FunctionalTests/CorsMiddlewareFunctionalTest.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.014s] TestLifetime Information: Starting test RunClientTests at 2018-10-12T19:53:52
| [0.001s] TestLifetime Information: Starting test RunClientTests at 2018-10-12T19:53:52
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /mnt/work/33bdfc1cae7b2a38/modules/CORS/samples/SampleDestination/bin/Release/netcoreapp2.2/SampleDestination.dll --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [0.020s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.021s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.021s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_CONTENTROOT=/mnt/work/33bdfc1cae7b2a38/modules/CORS/samples/SampleDestination
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 56831
| [0.264s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: SampleDestination.Startup[0]
| [0.264s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Setting up CORS middleware to allow clients on http://asp-ubuntu1604-01:9001
| [0.366s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| [0.366s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /mnt/work/33bdfc1cae7b2a38/modules/CORS/samples/SampleDestination/bin/Release/netcoreapp2.2
| [0.367s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://[::]:9000
| [0.368s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [0.373s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://[::]:9000/
| [0.381s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [0.381s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /mnt/work/33bdfc1cae7b2a38/modules/CORS/samples/SampleOrigin/bin/Release/netcoreapp2.2/SampleOrigin.dll --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [0.382s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.383s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.383s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_CONTENTROOT=/mnt/work/33bdfc1cae7b2a38/modules/CORS/samples/SampleOrigin
| [0.388s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 56864
| [0.752s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| [0.756s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /mnt/work/33bdfc1cae7b2a38/modules/CORS/samples/SampleOrigin/bin/Release/netcoreapp2.2
| [0.757s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://[::]:9001
| [0.757s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://[::]:9002
| [0.758s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [0.758s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://[::]:9002/
| [4.093s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Attempting to cancel process 56864
| [4.113s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Unable to terminate the host process with process Id '56864
| [4.114s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application is shutting down...
| [4.114s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '3.732977' seconds
| [4.115s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Atte
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @Eilon (because the bot doesn't know who else to pick)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
@mkArtakMSFT / @javiercn - is this a new CORS failure?

**Comment by javiercn** [comment]
@Eilon Seems like it. I'm giving this to @pranavkm as I'm not familiar with the infrastructure

**Comment by pranavkm** [comment]
Yup. I'll check

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=576787&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2 at 1:49:09 PM:
- RunClientTests

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=577063&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2 at 4:38:37 PM:
- RunClientTests

**Comment by pranavkm** [comment]
Should be fixed now. https://github.com/aspnet/CORS/commit/8ad589c4d1be35232694e17f38de06c1614b213d helped me track down the issue

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=578253&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master at 12:00:52 PM:
- RunClientTests

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=578368&buildTypeId=XPlat_Windows_Win7_Universe) on master at 2:44:36 PM:
- RunClientTests

**Comment by javiercn** [comment]
@pranavkm?

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=579008&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 2:12:21 PM:
- RunClientTests

**Comment by pranavkm** [comment]
Fixed by increased timeout + more diagnostics when pupetteer setup fails:
