### ISSUE TITLE
Precompilation does not work when applications use path traversal

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#33]
Consider a page with

```
@{
   Layout = "../Shared/_Layout.cshtml";
}
```

This works when there's an underlying file provider that does path resolution. However once the app is precompiled and deployed, the view engine fails to resolve this path. The issue is that the lookup is of the format '/Views/Home/../Shared/_Layout.cshtml` whilst the key for the precompiled view is `/Views/Shared/_Layout.cshtml` and the view engine does not do the path traversal.

**Comment by pranavkm** [comment]
Keeping this open to add tests from https://github.com/aspnet/MvcPrecompilation/pull/32

**Comment by Bartmax** [comment]
I hit this issue yesterday and I fixed it replacing 
```
@{
   Layout = "../Shared/_Layout.cshtml";
}
```
with:
```
@{
   Layout = "_Layout";
}
```

**Comment by pranavkm** [comment]
That's the current workaround @Bartmax. I just checked in the fix for this in Mvc, so it should make it to the next release.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/MvcPrecompilation/pull/65
