### ISSUE TITLE
Are partial views supported?

### ISSUE THREAD

**Issue by fleed** [aspnet/MvcPrecompilation#34]
Using version `1.1.0-preview4-final` of **Design** and **Tools**.

If I have the following instruction in the `_Layout.cshtml`:

```csharp
@Html.Partial("_Account.cshtml")
```

and I compile using

```text
dotnet razor-precompile --embed-view-sources --configuration %publish:Configuration% --framework %publish:TargetFramework% --output-path %publish:OutputPath% %publish:ProjectPath%
```

I get the following runtime error
```text
Additional information: The partial view '_Account.cshtml' was not found. The following locations were searched:

_Account.cshtml
```

The website works if I comment the call to `Partial`

**Comment by pranavkm** [comment]
@fleed it's likely that you're running in to the same issue as https://github.com/aspnet/MvcPrecompilation/issues/27. Could you try using a view name or an absolute path: e.g.

`@Html.Partial("_Account")` or `@Html.Partial("/Views/Shared/_Account.cshtml")`.

**Comment by fleed** [comment]
@pranavkm your solution (`@Html.Partial("_Account")`) works, thank you.
Closing this one considering that you're already working on #27
