### ISSUE TITLE
Layout lookups with file extension cannot be found.

### ISSUE THREAD

**Issue by ctolkien** [aspnet/MvcPrecompilation#38]
Given a razor view which works when not-precompiled:

```csharp
@{
    Layout = "_BaseLayout.cshtml";
}
```
Results in an exception

```
System.InvalidOperationException: The layout view '_BaseLayout.cshtml' could not be located. The following locations were searched:
_BaseLayout.cshtml
```

Changing this to remove the file extension

```csharp
@{
    Layout = "_BaseLayout";
}
```

Works in both scenarios.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/MvcPrecompilation/issues/27. 

For the time being, we recommend using name based lookups (which essentially involves removing the extension) or app-root relative paths (e.g. `/Views/Shared/_BaseLayout.cshtml`)
