### ISSUE TITLE
Disable using precompiled views at runtime

### ISSUE THREAD

**Issue by henkmollema** [aspnet/MvcPrecompilation#39]
My application references a NuGet package that contains precompiled views. When developing, I want to use the local views in the project. However, the Razor view engine seems to pick precompiled views above local ones. Is it possible to configure or override this behavior? I've been looking the Razor view engine but can't seem to find the correct way to disable precompiled views.

**Comment by pranavkm** [comment]
There isn't a particularly good way to do this now - the goal was for precompilation to be used for deployed applications so the presence of the views binary was meant to be a switch. There's an "internal" API that you might let you workaround this for now:

```C#
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.ApplicationParts;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;

namespace Microsoft.AspNetCore.Mvc.Razor.Internal
{
    public class NonDevCompilerCacheProvider : ICompilerCacheProvider
    {
        public DefaultCompilerCacheProvider(
            IHostingEnvironment hostingEnvironment,
            ApplicationPartManager applicationPartManager,
            IRazorViewEngineFileProviderAccessor fileProviderAccessor)
        {
            IDictionary<string, Type> precompiledViews;
            if (hostingEnviroment.IsDevelopment())
            {
                precompiledViews = new Dictionary<string, Type>();
            }
            else
            {
                var feature = new ViewsFeature();
                applicationPartManager.PopulateFeature(feature);
                precompiledViews = feature.Views;
            }

            Cache = new CompilerCache(fileProviderAccessor.FileProvider, precompiledViews);
        }

        /// <inheritdoc />
        public ICompilerCache Cache { get; }
    }
}

// Startup
services.AddMvc();
services.AddTransient<ICompilerCacheProvider, NonDevCompilerCacheProvider>();
```

**Comment by henkmollema** [comment]
Thanks @pranavkm, figured it should be somewhere in `ICompilerCacheProvider`. I came up with an implementation of `IApplicationFeatureProvider<ViewsFeature>` which clears `Views` collection in the feature (which `ICompilerCacheProvider` in turn uses to populate the cache):

```csharp
public class NoCacheViewFeatureProvider : IApplicationFeatureProvider<ViewsFeature>
{
    public void PopulateFeature(IEnumerable<ApplicationPart> parts, ViewsFeature feature)
    {
        // Clear all the found pre-compiled views to force use of local views.
        feature.Views.Clear();
    }
}
```

The feature provider should be added to the `ApplicationPartManager`:
```csharp
var applicationPartManager = services.GetInstance<ApplicationPartManager>();
applicationPartManager.FeatureProviders.Add(new NoCacheViewFeatureProvider());
```

**Comment by pranavkm** [comment]
Nice, that's much nicer than what I came up with and doesn't mess with internals. Could we close this issue since this turns out to be a a pretty simple solution to the issue?

**Comment by henkmollema** [comment]
Yeah sure, thanks for the help!

**Comment by henkmollema** [comment]
@pranavkm did anything change regarding to this in 2.0? Or is this still "the way" to override the default pre-compilation behavior of MVC?

**Comment by pranavkm** [comment]
Not that I know of. Is it no longer working as expected?

**Comment by henkmollema** [comment]
No, it's still working fine. Just needed this workaround again and wondered if it got any better since then.

**Comment by ruchanb** [comment]
How about using only local views?
```
<PropertyGroup>
  <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
</PropertyGroup>
```

**Comment by henkmollema** [comment]
@ruchanb it's about _using_ the precompiled views, not generating them.

**Comment by Matthew-Bonner** [comment]
For others reading this, in 2.0 `Views` has been renamed to `ViewDescriptors`.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.compilation.viewsfeature.viewdescriptors?view=aspnetcore-2.0
