### ISSUE TITLE
Port "Tool produces a 0-byte binary when compilation fails" to 1.1.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#40]
Original issue https://github.com/aspnet/MvcPrecompilation/issues/35

**Comment by pranavkm** [comment]
cc @Eilon  \ @DamianEdwards

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by pranavkm** [comment]
Do we plan on releasing a project.json targeting update for the tool? Or is the plan to roll this fix in with the 1.1.0 RTM build of the package that targets csproj?

**Comment by Eilon** [comment]
Yeah, taking this out of the "patch" list because we can just do it in the RTM build of this, which hasn't shipped yet.

**Comment by pranavkm** [comment]
We don't have to do anything here. The fix is already part of the 1.1.0 release so this can be closed.
