### ISSUE TITLE
Use MvcPrecompilation in net452

### ISSUE THREAD

**Issue by techcap** [aspnet/MvcPrecompilation#41]
Can I use MvcPrecompilation in net452 or other full framework version?

**Comment by pranavkm** [comment]
Yes, the tool should works on all platforms AspNetCore supports. It should work if you're targeting net452. Are you seeing issues when you run it.

**Comment by techcap** [comment]
It works!!! Thank you very much.

I refered to below line in View Compilation section.
https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/
