### ISSUE TITLE
No executable found matching command “Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design”

### ISSUE THREAD

**Issue by codeimpossible** [aspnet/MvcPrecompilation#44]
### Functional impact
Can't compile razor views using v1.1.0 of Tools/Design libs.

### Minimal repro steps
1. Follow steps in [AspNetCore 1.1 announcement post](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/).
1a. Add a reference to “Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design” under the “dependencies” section.
1b. Add a reference to “Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools” under the tools section
1c. Add postpublish script (i also was able to repro with a postcompile script, i'll include that since it's what i'm looking to use)

```
"scripts": {
  "postcompile": "dotnet razor-precompile --configuration %compile:Configuration% --framework %compile:TargetFramework% --output-path %compile:OutputDir% %project:Directory%"
},
```

### Expected result
Views should be compiled to `<ProjectName>.PrecompiledViews.dll`

### Actual result
The following error is shown in the shell output:

```
No executable found matching command "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileDispatchCommand.Execute()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Internal.PrecompilationApplication.Execute(String[] args)
```

### Further technical details
I'm currently trying to build a Class Library with precompiled views. I've looked over the example projects in this repo, and I don't see anything obvious that would cause the error I'm seeing. I've included the output of `dotnet -v build` here:

```
Hudl.Marvel.Ui.Render> dotnet -v build
Telemetry is: Enabled
Project Hudl.Marvel.Ui.Render (.NETCoreApp,Version=v1.1) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
Compiling Hudl.Marvel.Ui.Render for .NETCoreApp,Version=v1.1
Running C:\Program Files\dotnet\dotnet.exe "C:\Program Files\dotnet\sdk\1.0.0-preview2-1-003177\csc.dll" -noconfig @D:\src\dotnet-ui-render\src\Hudl.Marvel.Ui.Render\obj\Debug\netcoreapp1.1\dotnet-compile-csc.rsp
Process ID: 8580
Running C:\Program Files\dotnet\dotnet.exe razor-precompile --configuration Debug --framework netcoreapp1.1 --output-path D:\src\dotnet-ui-render\src\Hudl.Marvel.Ui.Render\bin\Debug\netcoreapp1.1 D:\src\dotnet-ui-render\src\Hudl.Marvel.Ui.Render
Process ID: 10684
Running C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\jared.barboza\.nuget\packages\.tools\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools\1.1.0-preview4-final\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools.deps
.json --additionalprobingpath C:\Users\jared.barboza\.nuget\packages C:\Users\jared.barboza\.nuget\packages\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools\1.1.0-preview4-final\lib\netcoreapp1.0\dotnet-razor-precompile.dll --configuration Debug
--framework netcoreapp1.1 --output-path D:\src\dotnet-ui-render\src\Hudl.Marvel.Ui.Render\bin\Debug\netcoreapp1.1 D:\src\dotnet-ui-render\src\Hudl.Marvel.Ui.Render
Process ID: 9820
projectdependenciescommandresolver: D:\src\dotnet-ui-render\src\Hudl.Marvel.Ui.Render\bin\Debug\netcoreapp1.1\Hudl.Marvel.Ui.Render.runtimeconfig.json does not exist
No executable found matching command "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileDispatchCommand.Execute()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Internal.PrecompilationApplication.Execute(String[] args)
```

Here is my project.json as well:

```
{
    "name": "Hudl.Marvel.Ui.Render",
    "version": "1.0.0-*",
    "buildOptions": {
      "debugType": "portable"
    },
    "packOptions": {
      "files": {
        "include": ["content/**/*.*"],
        "mappings": {
          "lib/": "obj/precompiled/"
        }
      }
    },
    "dependencies": {
        "System.ComponentModel.TypeConverter": "4.3.0",
        "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.1.0",
        "Microsoft.AspNetCore.Mvc.Razor": "1.1.0",
        "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design": "1.1.0-*",
        "Microsoft.AspNetCore.Html.Abstractions": "1.1.0",
        "Microsoft.AspNetCore.Razor.Runtime": "1.1.0",
        "Microsoft.Extensions.FileProviders.Embedded": "1.1.0",
        "Newtonsoft.Json": "9.0.2-beta1"
    },
    "tools": {
      "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools": "1.1.0-*"
    },
    "scripts": {
      "postcompile": "dotnet razor-precompile --configuration %compile:Configuration% --framework %compile:TargetFramework% --output-path %compile:OutputDir% %project:Directory%"
    },
    "frameworks": {
      "netcoreapp1.1": {
        "dependencies": {
          "Microsoft.NETCore.App": {
            "version": "1.1.0-*",
            "type": "platform"
          }
        }
      }
    }
}
```

**Comment by pranavkm** [comment]
@codeimpossible I think you might be running in to a limitation of CLI tools - https://github.com/dotnet/cli/issues/2645 - that prevents them from working with class libraries. This should get fixed when the tooling gets to RTM. 

In the meanwhile, a workaround is to create an "executable". This would require specifying `emitEntryPoint: true` under the `buildOptions` node. See https://github.com/aspnet/MvcPrecompilation/blob/dev/testapps/ClassLibraryWithPrecompiledViews/project.json#L3-L6. Here's some of the additional code we have in our end-to-end test to produce a package from the project: https://github.com/aspnet/MvcPrecompilation/blob/dev/test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/ApplicationConsumingPrecompiledViews.cs#L65-L88

**Comment by codeimpossible** [comment]
@pranavkm success! adding both the lines you linked in https://github.com/aspnet/MvcPrecompilation/blob/dev/testapps/ClassLibraryWithPrecompiledViews/project.json#L3-L6 to my `project.json` and including a basic `Program.cs` allowed me to precompile the views. Thanks for the fast response!

**Comment by codeimpossible** [comment]
@pranavkm Thanks for your help with my earlier issue, I was hoping I could ask a few other questions. 

I'm currently trying to use view compilation tooling to compile a few layouts and a _ViewImports into a nuget package to reference them in a aspnetcore application. This doesnt seem to be possible, I can add the PrecompiledViews.dll to the nuget package, but the PrecompiledViews assembly doesn't seem to get referenced in the project when I add it. So to shorten this down to two questions:

- Is this use case currently supported and I'm just missing some steps, or will it be supported eventually?
- is there any way to rename the PrecompiledViews.dll or have the views be contained in the current project?

**Comment by pranavkm** [comment]
The scenario should work - that's basically what the test app I listed earlier does. Can you verify that the directory structure inside the package (you can extract it as a zip file or use zip archive view like 7-zip) looks like this:

```
/
C:.
│   ClassLibraryWithPrecompiledViews.nuspec
│   [Content_Types].xml
│
├───lib
│   ├───net451
│   │       ClassLibraryWithPrecompiledViews.exe
│   │       ClassLibraryWithPrecompiledViews.PrecompiledViews.dll
│   │       ClassLibraryWithPrecompiledViews.PrecompiledViews.pdb
│   │
│   └───netcoreapp1.0
│           ClassLibraryWithPrecompiledViews.dll
│           ClassLibraryWithPrecompiledViews.PrecompiledViews.dll
│           ClassLibraryWithPrecompiledViews.PrecompiledViews.pdb
│           ClassLibraryWithPrecompiledViews.runtimeconfig.json
│
└───_rels
        .rels
```

You might only have the `netcoreapp1.1`  TFM in your lib directory.

> is there any way to rename the PrecompiledViews.dll 
Not out of the box. You might be able to write a custom feature provider with a different extension if you'd like: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs#L21

> or have the views be contained in the current project
Unfortunately not. `dotnet build` does not for a model that supports this. We attempted to modify the assembly after the fact, but that was super messy. Plus with the current approach, runtime (dynamic) view compilation and build time compilation behave the same so it's less likely to produce odd problems due to differences in the compilation model.

**Comment by codeimpossible** [comment]
@pranavkm yep my nuget package looks exactly like the structure you have and i've added it to my mvc site. The ViewImports doesn't seem to be run (tag helpers and base classes for views aren't being setup) and I'm not sure how to reference the layout from within my view - which resides in the mvc site. I've tried using the layout name: 

```
@{
    Layout = "_MarvelLayout";
}
```

but this doesn't work, i get the "the view could not be found" error: 

```
Message=The layout view '_MarvelLayout' could not be located. The following locations were searched:
/Views/Home/_MarvelLayout.cshtml
/Views/Shared/_MarvelLayout.cshtml
```

**Comment by pranavkm** [comment]
@codeimpossible, unfortunately `_ViewImports` are a Razor parse time feature (cc @NTaylorMullen \ @rynowak - is this changing in Razovelution?) and consequently having a compiled view doesn't help here. You'd have to have the actual cshtml embedded in your binary (`--embed-view-sources`) and add an `EmbeddedFileProvider` for the precompiled assembly. 

The syntax for Layout looks correct. If you have a decompiler (ILSpy \ dotPeek), have a look at the `__PrecompiledViewCollection` type in the precompiled assembly. It should tell what the paths the views were compiled with. Additionally, precompiled view lookups are case sensitive (See https://github.com/aspnet/MvcPrecompilation/issues/37). Make sure you have the casing right.

**Comment by Eilon** [comment]
@pranavkm what is the work for us to do here?

**Comment by pranavkm** [comment]
We've completely rehauling how precompilation gets invoked, so the original issue is certainly no longer going to be valid. @codeimpossible, I'd recommend filing a separate work item for the other issue simply to avoid work item scope creep.
