### ISSUE TITLE
MvcPrecompilation and VS2017 UX

### ISSUE THREAD

**Issue by nielstanis** [aspnet/MvcPrecompilation#53]
Not sure if this is the right location to ask this question, but I'm going to give it a shot :smile: 
Will there be any direct support from the VS2017 UI to the precompilation (e.g. like the way we can do it in VS 2015 with publish and configure it)?

**Comment by pranavkm** [comment]
@nielstanis for VS 2017 (i.e. csproj based projects), we converted the tool to be an MSBuild target. The plan is for `Microsoft.AspNetCore.Mvc` to bring this target in by default and for precompilation to be enabled by setting a flag in the project, similar to how `MvcBuildViews` worked in Mvc 5. That said, having an UI might be nice - have the publish tool pass in the property to cause view compilation. @DamianEdwards thoughts on this?

**Comment by DamianEdwards** [comment]
We could certainly have some UI on the project property pages for configuring view compilation. Beyond just enabling/disabling it on build/publish, what else would it make sense to be able to configure?

**Comment by nielstanis** [comment]
So from past implementations in VS there we're options like 'Allow precompiled site to be updateable' in the configure section if you perform a precompilation of e.g. ASP.NET MVC application.  Configuring that will fully embed the views in the DLL and that's the behavior that I needed. 
Not seeing that option being available in one of the MvcPrecompilation arguments I'm assuming that won't be something to consider for the UI. I do see an option called 'Embed views' which can be a UI candidate. The rest of the settings look to me as something that will be derived from the project structure.

**Comment by pranavkm** [comment]
> So from past implementations in VS there we're options like 'Allow precompiled site to be updateable' in the configure section if you perform a precompilation

We don't currently support precompiled updateable views so having a UI option to enable it seems unlikely. You could look at something like https://github.com/aspnet/MvcPrecompilation/issues/39 if you'd like to use views on disk over precompiled views.

**Comment by nielstanis** [comment]
Thanks @pranavkm! Maybe a bit different than how I explained in my previous message but in our situation we want to views not to be update-able (not using any views on disk) and that's exactly what the current behavior of MvcPrecompilation is.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. This is a fairly advanced area and we feel that having additional UI for it in VS would probably complicate things for most users.
