### ISSUE TITLE
Add support for migrating the precompilation tool

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#55]
`dotnet migrate` understands specific AspNetCore tools and migrates them to the right MSBuild equivalent. We need to add support for migrating the precompilation tool for the RC3 release.

This includes

a. Removing the CLI tool reference (Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools)
b. Renaming the package reference Microsot.AspNetCore.Mvc.Razor.ViewCompilation.Design -> Microsot.AspNetCore.Mvc.Razor.ViewCompilation and update it’s version
c. Removing the postpublish step that invoked the old tool
d. Add `<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>` in the csproj.

According to @livarcocc, the first two are pretty simple. (c) requires doing something along the lines of https://github.com/dotnet/cli/pull/4897. Might have to figure out what we need for (d).

cc @DamianEdwards \ @Eilon for tracking

**Comment by Eilon** [comment]
This sounds good. Let's do (d) only if (c) matches.
