### ISSUE TITLE
Indentation and spacing inconsistent in 'build/common.targets'

### ISSUE THREAD

**Issue by Eilon** [aspnet/MvcPrecompilation#57]
I &nbsp; mean , &nbsp; come &nbsp; on!&nbsp;&nbsp;

The indentation of the elements is inconsistent. And also there are some double-spaces before some `/>` sections.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/MvcPrecompilation/commit/501540c76e32abb5ae49d1c3e9730b63eb38aa4c
