### ISSUE TITLE
Precompile includes view files found in obj and bin folders of project

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/MvcPrecompilation#59]
The view compilation tool should exclude `obj` and `bin` folders by default. Right now, it finds all views under the project and includes them. Views often end up in `obj` due to publish using it as a temporary storage location, and in `bin` because the default publish output path is under `bin`. This results in compiled view assemblies that are much larger than necessary.

**Comment by DamianEdwards** [comment]
@pranavkm @Eilon

**Comment by Eilon** [comment]
Is there a "reliable" way of excluding these folders?

That is, it seems like there are two approaches:

1. Exclude stuff we don't want. Problem: We might not know all the things to exclude.
2. Include stuff we do want. Is it possible to take all the CSHTML files within the "Content" glob or similar?

**Comment by DamianEdwards** [comment]
Ultimately the application owns the place views are search for, and the view engine defaults to `IHostingEnvironment.ContentRoot`, which is set in the application. In our templates, that's set to CWD, but the app can do whatever it likes.

If possible, it would seem best to have the target default to using all `<Content />` items in the project that end with `.cshtml`, with a property that can be used to change it. I'm not sure if the default content globs automatically exclude things like `bin` and `obj` or if we'll have to exclude that ourselves.

**Comment by Eilon** [comment]
Let's fix for this tool's "RTM".

**Comment by pranavkm** [comment]
> 

It does exclude build output directories - 

* https://github.com/dotnet/sdk/blob/9d0b7a7b268eea4fc223be0935353cdddb99f5c7/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.targets#L32
* https://github.com/aspnet/websdk/blob/dev/src/Web/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L27

We could use the list of `Content` files from the csproj as the source of truth and that should generally fix the issue. The only concern is that if you `exclude` a file from inside VS but leave it in the output directory, the view engine would still discover it, at least during F5 \ `dotnet run`. Publish wouldn't include it and consequently the view engine wouldn't discover it on a published site. Maybe using the proj file as the source of truth is the right thing to do.

**Comment by Eilon** [comment]
This sounds fine to me in general. As far as the F5 scenario finding "excluded" views, I'm not too concerned about that. @DamianEdwards ?
