### ISSUE TITLE
Need to add E2E test that builds and publishes an MVC app w/ various compilation settings

### ISSUE THREAD

**Issue by Eilon** [aspnet/MvcPrecompilation#62]
Some scenarios to cover:
1. A matrix of true/false combinations to enable view compilation, and to control whether views are published
2. A matrix of debug/release combos, e.g. build debug, then publish as release

And, umm, other stuff!

**Comment by pranavkm** [comment]
We have features covered by tests. Added documentation for the settings as part of #156.
