### ISSUE TITLE
[Discussion] Microsoft.AspNetCore.Mvc.ViewCompilation 1.1.0-msbuild3-update1 released

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#71]
Discussion for https://github.com/aspnet/Announcements/issues/217

Today, we released a version of [`Microsoft.AspNetCore.Mvc.Razor.ViewCompilation`](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/1.1.0-msbuild3-update1) that supports MsBuild based projects as part of the January 27th RC release of Visual Studio 2017 (https://blogs.msdn.microsoft.com/visualstudio/2017/01/26/update-to-visual-studio-2017-release-candidate). 

If you were previously referencing `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design` in your project.json based applications that was migrated to csproj, your application might have a `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation` v1.1.0-msbuild3-final package. The update1 release of this package addresses some significant pain points discovered in the 1.1.0-msbuild3-final build of the package. See https://github.com/aspnet/MvcPrecompilation/issues?q=is%3Aissue+milestone%3A1.1.0-msbuild3-update1+is%3Aclosed for a list of the fixed issues.

To enable view compilation in a csproj based application,

1. Ensure your application is referencing the `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation` package. For e.g. your csproj would say:
`<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0-msbuild3-update" PrivateAssets="All" />`

2. Set the `MvcRazorCompileViewsOnPublish` property in the project enabling view compilation on publish:
```xml
<PropertyGroup>
  ...
  <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
  ...
</PropertyGroup>
```

Use https://github.com/aspnet/MvcPrecompilation/issues/71 for questions and further discussion.

**Comment by ctolkien** [comment]
Just to clarify, if we're still on `project.json` we should skip this for now?

**Comment by GuardRex** [comment]
Is it possible to get it running with nightly bits? I don't see the precompiled view DLL when I set things up this way :point_down: and `dotnet publish -c Release -r win10x64`.

### `csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <MvcRazorCompileViewsOnPublish>true</MvcRazorCompileViewsOnPublish>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.2.0-*" PrivateAssets="All" />
  </ItemGroup>

</Project>
```
### Feeds
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v2/" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
### Enviornment
```
.NET Command Line Tools (1.0.0-rc4-004706)

Product Information:
 Version:            1.0.0-rc4-004706
 Commit SHA-1 hash:  e38bc4950c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004706
```

**Comment by GuardRex** [comment]
Couple of questions:
1. There's a fallback to views if the DLL isn't present, correct? Is that relevant tho? ... Under what scenario(s) would the precompiled views DLL deployed but it falls back to using ordinary views anyway?
2. How reliable are precompiled views? If reliable, can we dump the compilation context and always run the app on the precompiled views? Then, can we further stop `Sdk.Web` from even adding the uncompiled views to the published output?

**Comment by pranavkm** [comment]
@ctolkien - yes, the `1.1.0-preview4-final` versions of `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design` and `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools` are the most recent, and possibly the final, set of packages targeting project.json. The MSBuild based tooling is generally incompatible with project.json based projects and vice-versa.

@GuardRex, thanks for noticing that! Fixed the announcement.

**Comment by guylando** [comment]
Hi,
The Microsoft.AspNetCore.Mvc.Razor.Precompilation version 1.1.0-msbuild3-update1 uses version 1.1.0.0 of Microsoft.AspNetCore.Mvc.Razor, Microsoft.AspNetCore.Mvc.Core, Microsoft.AspNetCore.Mvc.Razor.Host.
However in my solution I upgraded those packages to 1.1.1 after the security bulletin which was published.
So I had error regarding not finding 1.1.0.0. I solved them by adding App.Config file to my project and writing there:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime>
  
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.AspNetCore.Mvc.Razor" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.AspNetCore.Mvc.Core" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.AspNetCore.Mvc.Razor.Host" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
</runtime>
</configuration>

HOWEVER: Now on public, Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.exe is throwing the following errors:
EXEC(6,49): Error CS0826: No best type found for implicitly-typed array
EXEC(6,49): Error CS1503: Argument 1: cannot convert from '?[]' to 'System.Collections.Generic.IReadOnlyList<Microsoft.AspNetCore.Mvc.ApplicationParts.ViewInfo>'

So my guess is that those dependencies changed their code from 1.1.0 to 1.1.1 in a way that currently breaks Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.exe code.

So the easiest solution would be if you can publish a patch to version 1.1.0-msbuild3-update1 which is compiled with the security bulletin versions 1.1.1 of the mentioned libraries.

Or tell me where I can find source code of version 1.1.0-msbuild3-update1 and I will recompile it myself with appropriate references and code fixes.

P.S: I tried also using the newer prerelease versions of Microsoft.AspNetCore.Mvc.Razor.ViewCompilation but it breaks my solution because my solution currently uses versions 1.1.0, 1.1.1 of all libraries.

**Comment by awcab** [comment]
Is it possible to have this enabled when just building and not deploying?

**Comment by GuardRex** [comment]
@swcab If by "deploying" you mean "publishing," a build automatically accompanies publishing. Do you mean "Debug" vs. "Release"? If so, you could set a `Condition` to control it ...
```
<MvcRazorCompileOnPublish Condition=" '$(Configuration)' == 'Debug' ">true</MvcRazorCompileOnPublish>
```

**Comment by awcab** [comment]
@GuardRex I did mean publish.  Currently I'm only seeing compile errors on package or publish and not just when I build.  Maybe I'm missing another setting?

**Comment by GuardRex** [comment]
@awcab Ah ... I see. It sounds like something else has gone wrong then. I suggest opening a new issue in this repo with the details about the compile errors you're seeing. If you can setup a small repro to go with the issue, that's often helpful. If setting up a repro project would be very time-consuming, then just describe the situation ... they might not need a repro to help you solve the problem(s). 

WRT controlling it on build vs. publish, I'm not aware of how that's done (idk if there is a property you can check). AFAIK publish automatically triggers a build, so there wouldn't be a simple way to distinguish between the two. One of the dev team cats will probably jump in here and tell us if there's a way.

**Comment by awcab** [comment]
@GuardRex Just to be clear I'm talking about compile errors in my Views.  I want compile errors to fail the build and not have to go through a package/publish step.  Currently, publish does trigger a build, but I would like to see these just during a build without a publish.  This is the way it happened with pre-Core Asp MVC.

**Comment by GuardRex** [comment]
@awcab See if you can chat with @dasmulli or some of the other devs on Slack. It might be quicker to get assistance given that its the weekend. The self-signup is via: http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by pranavkm** [comment]
@awcab does https://github.com/aspnet/MvcPrecompilation/issues/83#issuecomment-279027377 address your scenario?

**Comment by dasMulli** [comment]
So @GuardRex asked to make it work for build & publish.. came up with that:

```xml
    <Target Name="SetMvcRazorOutputPath">
      <PropertyGroup>
        <MvcRazorOutputPath>$(OutputPath)</MvcRazorOutputPath>
      </PropertyGroup>
    </Target>

    <Target Name="_MvcRazorPrecompileOnBuild"
            DependsOnTargets="SetMvcRazorOutputPath;MvcRazorPrecompile"
            AfterTargets="Build" 
            Condition=" '$(IsCrossTargetingBuild)' != 'true' " />

     <Target Name="IncludePrecompiledViewsInPublishOutput"
            DependsOnTargets="_MvcRazorPrecompileOnBuild"
            BeforeTargets="PrepareForPublish"
            Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
      <ItemGroup>
        <_PrecompiledViewsOutput Include="$(MvcRazorOutputPath)$(MSBuildProjectName).PrecompiledViews.dll" />
        <_PrecompiledViewsOutput Include="$(MvcRazorOutputPath)$(MSBuildProjectName).PrecompiledViews.pdb" />
        <ContentWithTargetPath Include="@(_PrecompiledViewsOutput->'%(FullPath)')"
            RelativePath="%(_PrecompiledViewsOutput.Identity)" 
            TargetPath="%(_PrecompiledViewsOutput.Filename)%(_PrecompiledViewsOutput.Extension)" 
            CopyToPublishDirectory="PreserveNewest" />
      </ItemGroup>
    </Target>
```

**Comment by pranavkm** [comment]
You could possibly replace the second target with the `MvcRazorCompileOnPublish` property. The one issue with enabling it on build and leaving the precompiled view around is that you lose the edit-cshtml-and-refresh-the-browser experience. If that's something you want to keep, remove the binary from the output path after it's compiled. This should make the behavior analogous to the [`MvcBuildViews`](https://blogs.msdn.microsoft.com/jimlamb/2010/04/20/turn-on-compile-time-view-checking-for-asp-net-mvc-projects-in-tfs-build-2010) feature from Mvc <= 5.

**Comment by dasMulli** [comment]
Or replace this from my example
```xml
<MvcRazorOutputPath>$(OutputPath)</MvcRazorOutputPath>
```
with
```xml
<MvcRazorOutputPath>$(IntermediateOutputPath)</MvcRazorOutputPath>
```

That way, the views will be checked on every build but only used when publish (since the dll isn't dropped next to the main dll on build).

**Comment by GuardRex** [comment]
> I want compile errors to fail the build

Would it be cleaner to fail a unit test rather than inject all of that into the project file? If so, what would a unit testing approach look like? (just curious)

**Comment by awcab** [comment]
@pranavkm It would be nice to keep edit and refresh. However, this is part of a service fabric application and so far I lost any sort of edit and refresh, even js and html. If anyone knows how to get that working that would be fantastic.

**Comment by awcab** [comment]
@GuardRex IMO unit tests should be used to check runtime behavior.  Earlier detection is always better.

**Comment by GuardRex** [comment]
@awcab Just curious: As a feature request, are you hoping for something simple like `<MvcRazorCompileOnBuild>` that applies notwithstanding how `MvcRazorCompileOnPublish` is set? [Things would get a little hairy if the reverse were true ... build is set to false but publish is set to true.]

**Comment by awcab** [comment]
@GuardRex Yes, I think that's exactly what I would like.  Wasn't the the previous default behavior?

**Comment by GuardRex** [comment]
@awcab idk on the previous behavior. They'll say if they want that in a feature request issue opened separately. What @dasMulli and @pranavkm show is wonderful, but it seems kind'a heavy for such a simple requirement. I just wanted to clarify what would be the simplest public feature from a UE perspective in case this becomes a real ask (i.e., a real feature request).

**Comment by awcab** [comment]
Just FYI, this works well except that compile errors shown in the error list are not hotlinked to the source.  I realize this is probably a VS issue.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
