### ISSUE TITLE
Don't infer runtime built on through target framework built for

### ISSUE THREAD

**Issue by dasMulli** [aspnet/MvcPrecompilation#72]
I don't think that it is a good idea to infer the framework / OS you are building ON through the target framework you are building FOR. The NuGet package ships with binaries for netcoreapp1.1 and net451 and tries to run them during build depending on the framework building for.

This crashes horribly when trying to build for `net461` from a macOS machine.
Ideally, [like the SDK](https://github.com/dotnet/sdk/blob/d8e9a98dafd629010c13c622a00f72a4343a839e/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.Common.targets#L19), the build targets should select the library / binary based on the `MSBuildRuntimeType` property.

Just [running an exe](https://github.com/aspnet/MvcPrecompilation/blob/32cd737b62da8f689aebc52f6b35339f7331e575/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/net451/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets#L32-L34) also probably doesn't play well on mono when using a mono-based msbuild with the SDKs.

I have attached a sample project that I would expect to build cross-platform for `netcoreapp1.1` and `net461`:
[example.zip](https://github.com/aspnet/MvcPrecompilation/files/736781/example.zip)

cc @pranavkm

**Comment by nwoodthorpe-test1** [comment]
❤️ 💚 💙 💛 💜![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f5a4.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f499.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f494.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f468-2764-1f468.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f469-2764-1f469.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49a.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49f.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f60d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f63b.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f493.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f497.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2665.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2763.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f618.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49c.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49e.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f496.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f495.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49b.png?v7 "Logo Title Text 1")Seen by Nathaniel Woodthorpe at 00:05

**Comment by ctolkien** [comment]
I think this is the issue I'm hitting.

I have a target framework of `net461`, however if I try and publish without a `RuntimeIdentifier` specified, the publish process fails with:
>The command "bin\Release\net461\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x86.exe @"obj\Release\net461\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 9009.

There is no executable with that name on disk.

If I specify a RID, then it works, however what I'm publishing _from_ has little bearing on what I'm publishing _to_.

**Comment by dasMulli** [comment]
Another side effect of this is that cross-compiling between Mac/linux(x64/arm)/win is broken:

```
$ dotnet new mvc
$ dotnet restore -r linux-x64
$ dotnet publish -r linux-x64

  A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/martin/testproj/bin/Debug/netcoreapp2.0/linux-x64/'.
/Users/martin/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0-preview1-final/build/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(26,5): error MSB3073: The command "dotnet exec --runtimeconfig "/Users/martin/testproj/bin/Debug/netcoreapp2.0/linux-x64/testproj.runtimeconfig.json" --depsfile "/Users/martin/testproj/bin/Debug/netcoreapp2.0/linux-x64/testproj.deps.json" "/Users/martin/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0-preview1-final/build/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj/Debug/netcoreapp2.0/linux-x64/microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 131. [/Users/martin/testproj/testproj.csproj]
```

**Comment by mkArtakMSFT** [comment]
We're not going to make any other significant enhancements to this feature, as we'll be replacing it with a better one.
