### ISSUE TITLE
Precompiled views are not generated for small footprint self-contained app

### ISSUE THREAD

**Issue by GuardRex** [aspnet/MvcPrecompilation#73]
Repro project: https://github.com/GuardRex/testselfcontained

This project fails to run due to another issue: https://github.com/aspnet/Configuration/issues/589
It also isn't having its `web.config` configured correctly: https://github.com/aspnet/websdk/issues/108

In addition, it also isn't having its views precompiled (no DLL) ...

![capture](https://cloud.githubusercontent.com/assets/1622880/22397626/6a5ab3e2-e53b-11e6-9547-111114c69ebd.PNG)

It will produce precompiled views (the DLL) if I convert it to a normal (not small footprint) self-contained app.

**Comment by pranavkm** [comment]
@GuardRex - was the incorrect web.config the underlying issue or did you happen to accidentally close this?

**Comment by GuardRex** [comment]
Nah ... I figured it's premature. I figured it would be best to wait until 2.0 ships and if it's still not working, I would open (or re-open these) issues at that time.

The main problem right now when it runs is a runtime error for https://github.com/aspnet/Configuration/issues/589, which I just confirmed is still happening. (I'm on `1.0.0-rc4-004732` now.)

```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.KeyValuePair`2[System.String,System.String]' to type 'System.Collections.DictionaryEntry'.
   at System.Linq.Enumerable.<CastIterator>d__35`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load(IDictionary envVariables)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder..ctor()
   at testselfcontained.Program.Main(String[] args)
```


It's also not producing precompiled views as described above. I just published it again ... no precompiled views file is there. If I flip it back over to non-small-footprint self-contained app, it works fine and precompiled views are produced.

![capture](https://cloud.githubusercontent.com/assets/1622880/22519573/653fbf72-e876-11e6-97ce-df69b4ace832.PNG)

The `web.config` problem is still happening. It comes out setup for `dotnet XXX.dll` instead of `XXX.exe`.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" 
                path="*" verb="*" 
                modules="AspNetCoreModule" 
                resourceType="Unspecified" />
    </handlers>
    <aspNetCore stdoutLogEnabled="true" 
                stdoutLogFile=".\logs\aspnetcore-stdout" 
                processPath="dotnet" 
                arguments=".\testselfcontained.dll" />
  </system.webServer>
</configuration>
```

The repro project is at https://github.com/GuardRex/testselfcontained

To set it up for small-footprint self-contained, use the ...
```
<TargetFramework>netstandard1.6.2</TargetFramework>
<NetStandardImplicitPackageVersion>1.6.2-*</NetStandardImplicitPackageVersion>
```
... instead of (comment these out) ...
```
<TargetFramework>netcoreapp2.0</TargetFramework>
<NetCoreAppImplicitPackageVersion>1.2.0-*</NetCoreAppImplicitPackageVersion>
```
... and uncomment the lines ...
```
<PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="1.2.0-*" />
<PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="1.2.0-*" />
```
... to publish, I'm using ...
```
dotnet publish -c Release -r win10-x64
```
cc/ @blackdwarf -- Correct me if I'm wrong, but at some point, someone there will do a full small-footprint, self-contained test and see if the guidance you have in the doc is correct, right? That's why I closed these issues: I guessed that someone would dogfood it on the team before 2.0 releases and there would perhaps be some new guidance. The problems I'm facing :point_up: are prob due to my having configured the small-footprint app incorrectly.

**Comment by GuardRex** [comment]
No longer a valid issue, since small footprint apps are not a supported scenario for 2.0+ (and only barely supported <2.0).
