### ISSUE TITLE
Problem with identifying problem with procompilation

### ISSUE THREAD

**Issue by msmolka** [aspnet/MvcPrecompilation#74]
I'm using 1.1.0-preview4-final tools.
Have couple of project all other compiling properly (they are much smaller)
Every time I'm trying precompile my portal I'm getting error:

Running Razor view precompilation.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error :  (5): Encountered end tag "a" with no matching start tag.  Are your start/end tags properly balanced?

I've tried both Debug and Release.
I've created new project from scratch (empty one, without single view in it and copied all my files except views) There is no single view and still have issue. 
Tried to remove other files but after removing half of them still having the issue.

Tried to compile tool separately to maybe debug the issue, hover I'm not able to make it work. I'm not able manually force it to properly run it from different folder (any advice?)

I've removed obj/bin folders 

Can you help me diagnose the problem? Debug precompilation or anything? This drives me crazy. After 5 hours of removing files, still cannot find the issue.

**Comment by pranavkm** [comment]
@msmolka - we fixed this issue as part of the 1.1.0 release (https://github.com/aspnet/MvcPrecompilation/commit/2276c9eafeb351a5d4b000ad0723d02ec7a52f64). For the preview4 tools, there isn't a great way to diagnose the issue. Essentially all the tool does is iterate over the ContentRoot (unless modified this is the working directory) and locate all cshtml files recursively (essentially `dir /s *.cshtml`) so perhaps that might be a way to locate the problematic view. 

Alternative, if you have a repository you can share with a repro, feel free to post it here and we can dig in to it.

**Comment by msmolka** [comment]
Is this fix available anywhere to download, or you can provide nupkg file? So I could try. 

The strange thing is related to no views at all. Even if I delete all views from my project, no single cshtml file, I still have this error. Maybe it is cached somewhere? But I could identify the place where.

**Comment by pranavkm** [comment]
@msmolka unfortunately we're no longer producing updates to the package targeting project.json. If you intend on updating to the MSBuild based tooling, the package with this fix should become available on our nightly feed - `https://dotnet.myget.org/f/aspnetcore-dev/api/v3/index.json` in a bit. I need to merge some changes in.

**Comment by msmolka** [comment]
@pranavkm I would like to try, if you guide me (let me know where to find info) how to migrate in vs 2015 from project.json to msbuild. If it is even possible.

**Comment by pranavkm** [comment]
MSBuild based tooling specifically works with VS 2017. A migration guide is available here - https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/#upgrading-your-project-to-use-net-core-11.

**Comment by msmolka** [comment]
@pranavkm At this moment I'm not ready for VS2017. 

But I'd like to thank you for advice with finding wrong file (`dir /s *.cshtml`). It occurred to be under node_modules one. I was expecting to that folder will be ignored. I've reported separate bug: #75

This one can be closed.

**Comment by pranavkm** [comment]
@msmolka - thanks for the other work item. This is another issue that we addressed with the updated MSBuild based tool.
