### ISSUE TITLE
Precompilation should comply compile rules (exclude node_modules folder)

### ISSUE THREAD

**Issue by msmolka** [aspnet/MvcPrecompilation#75]
Hello
Last whole day I tried to find the problem with precompilation and find wrong view. 
After some advises from @pranavkm I finally found bad file. 
It occurred to be wrong file in one folders under node_modules. 
in project.json file I have following build option:

```json
"buildOptions": {
      "compile": {
        "exclude": [ "node_modules" ]
    }    
  },
```
so I was expected this folder will be excluded from compilation. But it is not. I don't now how it is planned to be solved in msbuild csproj files, but in my option there should be an option to exclude folders from compilation.

**Comment by pranavkm** [comment]
@msmolka - we addressed this with the msbuild tooling - https://github.com/aspnet/MvcPrecompilation/issues/59. Files specified in the project file (csproj) are the only ones included during compilation.
