### ISSUE TITLE
Add an option to disable publishing "refs" assemblies if compilation of views is enabled

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#76]
We'd have a flags similar to `MvcRazorExcludeViewFilesFromPublish` that allows disabling this feature. Relevant line of code in the SDK: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.PreserveCompilationContext.targets#L44-L47. We could ask the SDK team if they would consider adding a specific flag to disable publishing refs, but it would be safer to go with the assumption that this is unlikely to happen.

**Comment by pranavkm** [comment]
@Eilon - needs to be triaged for the 1.1.0 (tooling RTM release).

**Comment by Eilon** [comment]
We're kind of supposed to be shut down for this release.

@DamianEdwards any thoughts on priority of this?

**Comment by DamianEdwards** [comment]
I asked @pranavkm to do this. This would be the only change we make between msbuild3-update1 and RTW. As it is right now, we're leaving many MBs of assemblies in the publish output that otherwise don't have to be there when view pre-compilation is enabled. Would be great to get this in for the final release if possible.

**Comment by Eilon** [comment]
@pranavkm do you think you can get this in today or Monday?

**Comment by DamianEdwards** [comment]
FWIW I just did this manually in my own project and it worked: https://github.com/aspnet/live.asp.net/commit/d9efda86dd509cede7b35761a775c05ca935b0a8
This is what we'd be doing in the package by default, with the added condition for the opt-out property.

**Comment by Eilon** [comment]
@DamianEdwards do any project templates need to change to start using this new option?

**Comment by DamianEdwards** [comment]
No

**Comment by DamianEdwards** [comment]
The intent is it would be the default behavior when `<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>` is specified, which it already is in the templates.

**Comment by Eilon** [comment]
Ok, so by default when you use pre-compilation, you will typically no longer even be able to compile CSHTML at runtime. E.g. no more "dynamic" stuff. I think that's fine.

**Comment by DamianEdwards** [comment]
Correct, we'd remove the CSHTML files and refs from publish output by default.
