### ISSUE TITLE
ViewCompilation 1.1.0-msbuild3-final does not work with Microsoft.AspNetCore.Mvc 1.1.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#78]
Based on comment here - https://github.com/aspnet/MvcPrecompilation/issues/71#issuecomment-277443739

NuGet doesn't look at the `build` directory when determining what binding redirects to produce. Consequently running the exe fails since it can't find the 1.1.0 versions that it's compiled against.

**Comment by pranavkm** [comment]
cc @DamianEdwards \ @Eilon - could we do this along with #76?

**Comment by guylando** [comment]
@pranavkm when is 1.1.0-msbuild supposed to be published to nuget.org?

**Comment by Eilon** [comment]
@guylando we're just finishing some testing on it and we'll release it ASAP!

**Comment by ygoe** [comment]
The updated package is available today and works for me on .NET Framework 4.6.1. Thank you!
