### ISSUE TITLE
Clarification: compilation on build not supported?

### ISSUE THREAD

**Issue by guylando** [aspnet/MvcPrecompilation#83]
1)When I think about views compilation it seems like something I would also like to have as part of my solution build to find errors at this stage and not at runtime.
2)I have read the announcement https://github.com/aspnet/Announcements/issues/217 and it did not clarify whether compilation on solution build is something which is supported\going to be supported. There is the MvcRazorCompileOnPublish element in csproj, there is no MvcRazorCompileOnBuild element?

Can you please clarify this? And I guess a clarification in the announcement itself would help other people which were wondering about this also.

The visual studio 2017 tooling currently does not support views intellisense and I did not see a milestone for that so if there would be views intellisense then it would prevent the need for view compilation for the purpose of finding compilation errors in design time instead of runtime. But for the time being with razor views intellisense, the precompilation on build could serve this purpose.

**Comment by pranavkm** [comment]
Precompiled views are preferred cshtml files by Mvc. This takes away the edit the cshtml file and refresh in browsers that users are familiar with. Consecutively, we did not build a `MvcRazorCompileOnBuild` hook as part of 
our targets. That said, all it takes to enable view compilation as part of build is to invoke the `PrecompileRazorViews` build target. Here's what it would look like:

```xml
  <Target
    Name="PrecompileRazorViews"
    AfterTargets="Build"
    DependsOnTargets="MvcRazorPrecompile"
    Condition="'$(TargetFramework)'!=''">
       <!-- Remove the output assembly so it doesn't get used at runtime -->
       <Delete Files="$( _MvcRazorOutputFullPath)" Condition="Exists('$( _MvcRazorOutputFullPath)')" />
  </Target>
```

There's also an alternative to deleting the file listed in https://github.com/aspnet/MvcPrecompilation/issues/39#issuecomment-262450781, but you'd have to figure out how to wire up the feature conditionally.
