### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by ygoe** [aspnet/MvcPrecompilation#84]
I see this project seems to be related to NuGet package names I can find in a hidden corner of the web, but I have no idea where to start. I installed the latest Visual Studio 2017 RC and created a new Web application project with ASP.NET Core and .NET Core 1.1. (I've tried with .NET Framework 4.6.1 before but this NuGet package wasn't available for that runtime. I guess view compilation will only work with .NET Core.)

I found instructions to add something to project.json which doesn't exist anymore with VS 2017. I found `<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>` somewhere around here and added it to one of the PropertyGroups in the .csproj file, together with installing the `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools` package in version 1.1.0-preview4-final from the NuGet GUI. Nothing happened, no additional DLL on publish but still the Views directory.

Could you please add some words in the readme about how this is supposed to be used, with VS 2015 and 2017, and with different target runtimes? There are also a number of similar-named packages and random/incomparable version numbers which is totally confusing.

**Comment by pranavkm** [comment]
Have you looked at the announcement for the release of the msbuild tool - https://github.com/aspnet/MvcPrecompilation/issues/71? It has some instructions on what you'd need to do to get going with view compilation in AspNetCore Mvc Core. The preview* line of all AspNetCore tools were designed for project.json based applications and aren't compatible with the MSBuild project system.

**Comment by ygoe** [comment]
That works, thank you!
