### ISSUE TITLE
Views are not updated during publish when cshtml content is modified

### ISSUE THREAD

**Issue by mehmetilker** [aspnet/MvcPrecompilation#91]
In my MVC Core app MvcRazorCompileOnPublish is set true and I can not see my changes I made on view on published site. I have to run clean manually every time.
I tried to add "dotnet clean" job  on BeforeTargets="Publish" but does not work.

Is there anything I need to add my project configuration file ?

I am using Microsoft.AspNetCore.Mvc.Razor.ViewCompilation Version="1.1.0-msbuild4-final"
And others all latest version.

I did  not try MvcRazorCompileOnPublish=false to see if it is related but it should work as expected when it is true.

**Comment by pranavkm** [comment]
> In my MVC Core app MvcRazorCompileOnPublish is set true and I can not see my changes I made on view on published site.

The behavior is intentional - we currently don't support precompiled updateable views i.e once we discover a precompiled view, we do not look for the a cshtml file for the lifetime of the application. It's primarily the reason we did not enable this feature as part of build - we want to continue supporting the _edit cshtml and refresh browser_ behavior that developers are accustomed to. 

There are ways to remove discovered precompiled views at runtime (See https://github.com/aspnet/MvcPrecompilation/issues/39#issuecomment-262450781, https://github.com/aspnet/MvcPrecompilation/issues/83#issuecomment-279027377), but both of these are targeted at the startup discovery, not ongoing updates.

**Comment by mehmetilker** [comment]
I guess there is misunderstanding here. Problem is not happening when I hit F5 and run the project inside of VS (on Build in this case).

What I am doing is that, creating a "Publish Profile" with publish to a folders option and delete all existing files setting.

What Precompile view is doing, I assume, compiling cshtml files and merge them in single library.

Problem is that when I copy published, output files to my live product environment I do not see changes I have made on cshtml files.

If I do Clean Solution first then everything ok.

I guess when Precompilation run does not remove old library created for views. This is why publish action is copying old file.

**Comment by pranavkm** [comment]
To clarify here's what's happening:

1. Publish an application with precompilation enabled
2. Modify a cshtml file
3. Publish the application again

Expected:
Rendered view has the modified view content

Actual:
View content isn't updated.

Does this sound accurate?

**Comment by mehmetilker** [comment]
That's right. 
If do "Clean Solution" before every publish I can see the modified content (edits in cshtml file).

**Comment by Eilon** [comment]
Sounds broken to me...

**Comment by mehmetilker** [comment]
I just discovered that problem to see changes after publish was about my configuration.
I was zipping publish directory after publish with setting in MSBuild `<Target AfterTarget="Publish">`
I found out that zipping was working before publish complated. I have changed target definition to 
`<Target AfterTarget="AfterPublish">` and now it seems everything ok.
Configuration settings are little bit confusing.

Sorry for inconvenience.

**Comment by pranavkm** [comment]
Thanks for updating the issue @mehmetilker !

**Comment by GuardRex** [comment]
@mehmetilker 

> Configuration settings are little bit confusing.

There are some docs coming that will explain out the props and targets. It will take a little while before they're written, but I just wanted to let you know that many feel that way :point_up: and docs will help with the confusion.
