### ISSUE TITLE
Make Microsoft.AspNetCore.Mvc.Razor.ViewCompilation a default dependency of Microsoft.AspNetCore.Mvc

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#94]
The idea would be to have the package reference there by default. Setting `MvcRazorCompileOnPublish` would cause view compilation to light up. This would require moving the tool in to the Mvc repository.

**Comment by Eilon** [comment]
Given that the .All metapackage references everything already, I don't think this is needed.

cc @DamianEdwards FYI.
