### ISSUE TITLE
Add tests to verify tests work for both Debug and Release configurations

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#99]
Right now we publish test apps in the configuration tests are running. This doesn't give us enough coverage for `Debug` publishes in particularly on the CI where it always builds in `Release`. Based on https://github.com/aspnet/MvcPrecompilation/pull/97#discussion_r105547719, let's add some tests that verify debug and release configurations all the time.

**Comment by pranavkm** [comment]
@Eilon - I'd much rather we do a select few tests with `Debug` \ `Release`. These tests run linearly (not parallel), so doing all of them in both Debug and Release would double the time, something that would be nice to avoid. Particularly if we plan on doing #94 which might involve moving this repo code in to Mvc.

**Comment by Eilon** [comment]
Yeah just adding some specific ones is fine. I want to make sure we have good coverage of the various realistic scenarios apps will encounter.
